Initial payload output structure definition
defenseunicorns-labs/lula1 pull request #267
Opened 2024-02-23 00:03 UTC by meganwolf0

Added some initial structure for pulling more data from OPA queries, including specifying the actual boolean "validate" field to be evaluated, as well as additional observations that can be output in "remarks" section of observations. Also added a test for the field. 

Current limitation is that the field from rego only support string data - this is really more of a go constraint but I'm sure if we wanted to support additional types you could expand the definition of an "output.observation".

2024-02-23 17:36 UTC, brandtkeller commented on src/pkg/providers/opa/opa.go
> +		rego.Query(fmt.Sprintf("data.%s", validation)),
I'd like to weigh the pro/cons for splitting out this logic into multiple rego evaluations (as you have here) vs potentially a single evaluation that results in `resultValid` containing  a larger slice of items that we can iterate over. 

IE as it stands now - with the scenario you added we see `resultValid` contain `[{[true] map[]}]` for `data.validate.validate` which is appropriate. Then to my understanding we execute another `rego.eval()` for each obversation, which in the validation that has output results in `[{[hello world]map[]}]`.

What am I curious about is if we take it up one level on the initial `rego.eval` to the package and use for example `data.validate` we get `resultValid` containing `[{[map[test:hello world validate:true]] map[]}]`. If we know what the `validate` target is (either default or defined) - then could we not just iterate over all remaining elements in the slice and use those as `observations` and remove the need to re-evaluate the entire dataset for each?

2024-02-23 18:04 UTC, meganwolf0 commented on src/pkg/providers/opa/opa.go
> +		rego.Query(fmt.Sprintf("data.%s", validation)),
Yeah, I did think about/try to do this as a single evaluation then pull the items needed. The issue is when those fields are in indeterminate json structure, so there's really not a clean way for go to handle that (thinking especially when validate isn't a first level field, e.g., validate.result.validate or something). You have to like marshal and unmarshal each structure for it to become usable data - then at the end of the day you still need to know what the types you are expecting so it's just pretty ugly. (I can throw up a competing PR here to delve down this path, but when I was working this yesterday that was my first impulse and after writing some lines I ran away pretty fast, ha!)

If we decided to pre-determine structure as a requirement, then agreed a single eval would probably be more appropriate - I was just thinking we maybe would like to be flexible there. But obviously the world is our oyster as far as design choices go!

If you're concerned about the time it takes to run an `eval` that's certainly something we could try and understand more. I kinda wasn't clear on latency requirements for this.

2024-02-23 18:19 UTC, brandtkeller commented on src/pkg/providers/opa/opa.go
> +		rego.Query(fmt.Sprintf("data.%s", validation)),
You raise a good point that this reduces the surface of marshalling/unmarshalling and a lot of handling of indeterminate data. That coupled with this being an optional field that people can opt-in to makes the surface of required optimization low at this point in my opinion.

2024-02-23 18:20 UTC, brandtkeller commented on src/types/types.go
> +type Output struct {
Documentation can go a long way here - but if we were to step back and think about this from another providers context (that doesn't exist today) - are the names of these fields intuitive and flexible for use? 

words are hard...

2024-02-23 18:25 UTC, brandtkeller commented on src/pkg/providers/opa/opa.go
> +		if matched, ok := resultObv[0].Expressions[0].Value.(string); ok {
Given this is supporting data for an observation - might be a good time to add debug level logging to aid in the debugging process. If something is wrong in the execution of a single item there isn't anything in the output to indicate a problem occurred.

2024-02-23 18:47 UTC, meganwolf0 commented on src/types/types.go
> +type Output struct {
Yeah, I'm not sure if the output here would be reusable across other providers - mainly just because I don't actually know what the output from other providers would be. It seemed like `Payload` was pretty particular to OPA though (just thinking the `Rego` field specifically), so wondering if we can punt the thought exercise til we have another provider to consider? Although of course if you have particular words that you think would be more extensible/resonate better I am certainly not attached to these words!

2024-02-23 21:07 UTC, meganwolf0 commented
@brandtkeller - I added some debugging to the validation and observation OPA results, just in case there's some unexpected values there, the whole thing shouldn't crash out, it will just result in a "not-satisfied" evaluation (edit: it's only "not-satisfied" if validate isn't recognized as boolean, which I think was the behavior before, debugging now just tells you why). Also, updated test case for output. How fine-grained are we making these tests? This one really just checks that the `outputs` section with various parameters doesn't fail, but no checks on if the correct things are output. I've just been checking that by examination in assessment-reports...

2024-03-05 18:30 UTC, meganwolf0 commented
Updated the docs as part of this PR, moving to ready for review

2024-03-06 03:38 UTC, brandtkeller commented on docs/opa-provider.md
> +Optionally, an `output` can be specified in the `payload`. Currently, the default validation allowance/denial is given by `validate.validate`, which is really of the structure `<package-name>.<json-p
```suggestion
Optionally, an `output` can be specified in the `payload`. Currently, the default validation allowance/denial is given by `validate.validate`, which is really of the structure `<package-name>.<json-path-to-boolean-variable>`. If you have a desired alternative validation boolean variable, as well as additional observations to include, an output can be added to payload such as:
```

2024-03-06 03:42 UTC, brandtkeller commented on docs/opa-provider.md
> +    payload:
I updated documentation in #253 - but wanted to mention that this is an outdated payload that pre-dated `[]Resources` - forgot to update docs then - oops

2024-03-07 01:55 UTC, meganwolf0 commented on docs/opa-provider.md
> +Optionally, an `output` can be specified in the `payload`. Currently, the default validation allowance/denial is given by `validate.validate`, which is really of the structure `<package-name>.<json-p
updated typo

2024-03-07 01:55 UTC, meganwolf0 commented on docs/opa-provider.md
> +    payload:
updated this documentation example with the correct structure

2024-03-07 01:57 UTC, meganwolf0 commented
@brandtkeller - Merged main and from my perspective this is ready to go, might be nice to get other eyes on though if you think other thoughts would be good to evaluate the implementation. Also, there's one convo I'll leave to you to resolve if you feel it is.

2024-03-07 03:10 UTC, brandtkeller requested changes

2024-03-07 03:10 UTC, brandtkeller commented on src/test/e2e/outputs_test.go
> +		Assess("Validate Outputs", func(ctx context.Context, t *testing.T, config *envconf.Config) context.Context {
I'd like to see more specificity in the body of this test. `validate` is not a pass/fail from the command line exit code status - so additional scrutiny in testing to target a finding state or even a specific remark given the new functionality would suffice.

2024-03-07 03:10 UTC, brandtkeller commented on src/test/e2e/outputs_test.go
> +			err = validate.WriteReport(report, "assessment-results-outputs.yaml")
This is going to create a file that is git-ignored. For sake of cleanliness and local-dev maybe we should standardize on cleaning up these files in the `teardown` as done in `pod_validation_test.go`.

2024-03-07 20:51 UTC, meganwolf0 commented on src/test/e2e/outputs_test.go
> +		Assess("Validate Outputs", func(ctx context.Context, t *testing.T, config *envconf.Config) context.Context {
Thanks for the feedback - I definitely struggled to write good tests here. Really, I wanted to check that the validation responded properly and the observations got printed out. So I modified a bit to just check those data objects since really it's not a matter of checking that the report gets generated. It is a little hokey because it doesn't seem like there's an actual link from the validations UUIDs to observations where remarks are. Please look at the changes and let me know if there's a better structure to try and meet the intent.

2024-03-07 20:51 UTC, meganwolf0 commented on src/test/e2e/outputs_test.go
> +			err = validate.WriteReport(report, "assessment-results-outputs.yaml")
Removed this section as I don't think we need to check the `WriteReport` function, but can add back in if you think otherwise

2024-03-07 21:48 UTC, brandtkeller commented on src/test/e2e/outputs_test.go
> +		Assess("Validate Outputs", func(ctx context.Context, t *testing.T, config *envconf.Config) context.Context {
Appreciate the updates - more tangible as far as validating the execution worked as expected.

2024-03-07 21:49 UTC, brandtkeller approved these changes

2024-03-08 16:36 UTC, merged