feat(cmd): Create upgrade command implementing go-oscal revise.
defenseunicorns-labs/lula1 pull request #295
Opened 2024-03-06 20:50 UTC by mike-winberry

2024-03-07 02:29 UTC, meganwolf0 commented
So I tried this out on the tempo validation I've been working and it had the mildly annoying result of moving all the fields around and smashing down my formatted `description` field with all the payload data down into a single line... Wondering if that could be pretty printed out and ideally the backmatter could still be at end of the oscal file? I'm not entirely sure if the intended use of this is to create a file a user would continue to work with, so also maybe some documentation to go along with the intent/use case specified?

2024-03-07 13:52 UTC, brandtkeller commented
> So I tried this out on the tempo validation I've been working and it had the mildly annoying result of moving all the fields around and smashing down my formatted `description` field with all the payload data down into a single line... Wondering if that could be pretty printed out and ideally the backmatter could still be at end of the oscal file? I'm not entirely sure if the intended use of this is to create a file a user would continue to work with, so also maybe some documentation to go along with the intent/use case specified?

hhmm... yeah this makes a lot of sense that it would do this given the underlying sting datatype and how we write validations. Unfortunate side-effect - if there is anything we can do to retain that structure then great - otherwise it certainly adds more evidence to needing a system that is more compatible.

2024-03-07 16:27 UTC, mike-winberry commented
> So I tried this out on the tempo validation I've been working and it had the mildly annoying result of moving all the fields around and smashing down my formatted `description` field with all the payload data down into a single line... Wondering if that could be pretty printed out and ideally the backmatter could still be at end of the oscal file? I'm not entirely sure if the intended use of this is to create a file a user would continue to work with, so also maybe some documentation to go along with the intent/use case specified?

I will create a story to look into it and see what I can do today. My understanding right now as to why, is that the golang map is unordered, and since json and yaml are considered to also be unordered maps, the marshalling and unmarshaling process doesn't guarantee order. I have some ideas on how to deal with that but will have to play a bit in go-oscal today and see what works out. 

I think another thing that could be done is looking at yaml formatters and run one before output. (for the string issue).

2024-03-09 17:51 UTC, brandtkeller requested changes

2024-03-09 17:51 UTC, brandtkeller commented on src/test/e2e/pod_validation_test.go
> +			revisionOptions := revision.RevisionOptions{
Captures intent of the artifact version upgrade. Would like to offer an alternative this workflow:

Could we instead upgrade the component-definition defined at the beginning of the `Assess()` function? (Are there any constraints here?)

My thinking is that this would become a incredibly valuable E2E test if we know that writing and executing validations does not get corrupted by the `lula tools upgrade` process as we continue to develop. Our test suite to-date has confirmed that the existing structure works - so adding this should mean we know if any modification to validation or upgrade breaks any part of the E2E lifecycle. 

Open to feedback.

2024-03-12 16:31 UTC, mike-winberry commented on src/test/e2e/pod_validation_test.go
> +			revisionOptions := revision.RevisionOptions{
That component definition is currently failing lint so I am going to see if I can fix it. 
```yaml
valid: false
timeStamp: 2024-03-12T09:29:15.379401593-07:00
errors:
    - keywordLocation: /oneOf/2/properties/component-definition/$ref/properties/components/items/$ref/properties/control-implementations/items/$ref/properties/source/$ref/type
      absoluteKeywordLocation: http://csrc.nist.gov/ns/oscal/1.0/1.1.1/oscal-complete-schema.json#/definitions/URIReferenceDatatype/type
      instanceLocation: /component-definition/components/0/control-implementations/0/source
      error: expected string, but got null
    - keywordLocation: /oneOf/2/properties/component-definition/$ref/properties/metadata/$ref/properties/parties/items/properties/links/items/$ref/properties/href/$ref/format
      absoluteKeywordLocation: http://csrc.nist.gov/ns/oscal/1.0/1.1.1/oscal-complete-schema.json#/definitions/URIReferenceDatatype/format
      instanceLocation: /component-definition/metadata/parties/0/links/0/href
      error: '''<https://github.com/defenseunicorns/lula>'' is not valid ''uri-reference'''
      failedValue: <https://github.com/defenseunicorns/lula>
metadata:
    documentPath: src/test/e2e/scenarios/pod-label/oscal-component.yaml
    documentType: component-definition
    documentVersion: 1.1.1
    schemaVersion: 1.1.1
```

2024-03-12 16:51 UTC, mike-winberry commented on src/test/e2e/pod_validation_test.go
> +			revisionOptions := revision.RevisionOptions{
Fixed the component-definition and updated the Assess by upgrading to a temp file and then using that temp file.

2024-03-12 22:28 UTC, brandtkeller approved these changes
Functionality is working as I would expect. Appreciate updates / modifications and testing in a manner that won't modify existing artifacts.

2024-03-12 22:49 UTC, mike-winberry commented
Also I found the issue that @meganwolf0 was encountering. It has to do with trailing whitespace. It is a current issue with the go yaml implementation https://github.com/go-yaml/yaml/issues/880. But if all trailing spaces are removed it no longer serializes the block/folded strings into double quotes. And is something that could be brought into go-oscal where we trim all empty trailing spaces from lines.

2024-03-12 22:55 UTC, brandtkeller commented
@mike-winberry I need to think more about edge cases but otherwise that sounds like a great issue for go-OSCAL

2024-03-12 22:57 UTC, mike-winberry commented
> @mike-winberry I need to think more about edge cases but otherwise that sounds like a great issue for go-OSCAL

https://github.com/defenseunicorns/go-oscal/issues/167

Have this open right now. With the resulting after removing whitespace.

2024-03-13 03:59 UTC, merged