Lula Version Property
defenseunicorns-labs/lula1 pull request #307
Opened 2024-03-14 17:27 UTC by meganwolf0

Initial cut at specifying a Lula Version in the "Lula Validation" oscal fields. 
Changes
- New type `Description` for the description to be robust about marshaling that field
- New `IsVersionValid` function
- Updated component.go to do version checking
- Dependency on Hashicorp's go-version library to do the version constraint checking
  -> Since we are using their library, we are beholden to their rules - one of which is that "prerelease" version checks are just automatically denied. I think the logic is that prerelease versions are possibly unstable and shouldn't be used. This creates some issues if building from a branch - which maybe should be discouraged but probably needs to be fleshed out. Anyway, needed to create a clean NON_PRERELEASE_VERSION in the Makefile to account for this.

2024-03-14 18:35 UTC, brandtkeller requested changes

2024-03-14 18:35 UTC, brandtkeller commented on docs/version-specification.md
> +    description: |
formatting looks off in this example

2024-03-14 18:35 UTC, brandtkeller commented on src/pkg/common/oscal/component.go
> +			currentVersion := "v0.0.2" //config.CLIVersion
Should this be modified to be that `config.CLIVersion` mention?

2024-03-14 18:35 UTC, brandtkeller commented on src/types/types.go
> +	LulaVersion string                 `json:"lulaVersion" yaml:"lulaVersion"`
[no change required] thinking about a TBD standard on what convention we use for naming. should the convention align to OSCAL and `lula-version` or?

2024-03-14 18:35 UTC, brandtkeller commented on Makefile
> +NON_PRERELEASE_VERSION ?= $(if $(shell git describe --tags --abbrev=0),$(shell git describe --tags --abbrev=0),"UnknownVersion")
Want to consider implications here that `make build` will produce a binary with the same `lula version` output as that of the binaries we build as part of an official release. It can always be spoofed - but I think this helps quickly identifying a potentially modified binary from one that is straight from a release (If debugging remotely).

`git describe --tags` suffixes the tag name with the number of additional commits on top of the tagged object and the abbreviated object name of the most recent commit. EX: `v0.0.2-57-g33ed319`

Is there a way to set this as the default in the make args and then trim all items right of the semver?

2024-03-14 18:54 UTC, meganwolf0 commented on src/types/types.go
> +	LulaVersion string                 `json:"lulaVersion" yaml:"lulaVersion"`
I was wondering that too - I went with camel case since that's how we did the other fields in the description but if this is going to live in the oscal it does look a little funny to switch conventions

2024-03-14 18:58 UTC, brandtkeller commented on src/types/types.go
> +	LulaVersion string                 `json:"lulaVersion" yaml:"lulaVersion"`
It also isn't widely enforced on the unmarshall process - so while it appears either works - we should look to migrating `lula-version` and `resource-rule` to the dash-case in implementations (which apprarently doesn't break current camel-case...

2024-03-14 19:00 UTC, meganwolf0 commented on src/types/types.go
> +	LulaVersion string                 `json:"lulaVersion" yaml:"lulaVersion"`
We also use uppercase resourceRule fields too...

2024-03-14 19:01 UTC, meganwolf0 commented on docs/version-specification.md
> +    description: |
yeah it is, will fix and choose a better example, I just copy-pasted from my test file and forgot to clean it up

2024-03-14 19:07 UTC, meganwolf0 commented on Makefile
> +NON_PRERELEASE_VERSION ?= $(if $(shell git describe --tags --abbrev=0),$(shell git describe --tags --abbrev=0),"UnknownVersion")
yeah that's a much better solution, I'll modify to do that instead

2024-03-14 19:19 UTC, meganwolf0 commented on src/pkg/common/oscal/component.go
> +			currentVersion := "v0.0.2" //config.CLIVersion
should be fixed

2024-03-14 19:20 UTC, meganwolf0 commented on Makefile
> +NON_PRERELEASE_VERSION ?= $(if $(shell git describe --tags --abbrev=0),$(shell git describe --tags --abbrev=0),"UnknownVersion")
updated, I'll let you take a look again and check if it looks ok to you!

2024-03-14 22:19 UTC, brandtkeller commented on src/types/types.go
> +	LulaVersion string                 `json:"lulaVersion" yaml:"lulaVersion"`
💯 - it appears that the unmarshall doesn't care (would like to test this). I believe we should take a stance on using `dash case` given we're working within OSCAL - and on first glance doesn't seem to be a breaking change - more of an opinionated implementation.

2024-03-14 22:22 UTC, brandtkeller commented on src/types/types.go
> +	LulaVersion string                 `json:"lulaVersion" yaml:"lulaVersion"`
Thoughts on taking a stance on dash case and then cleanup/test the other fields in another issue?

2024-03-15 03:30 UTC, brandtkeller commented on src/types/types.go
> +	LulaVersion string                 `json:"lulaVersion" yaml:"lulaVersion"`
I lied... the mapstructure library is performing the decoding here. So the field name is honored instead of the intuited `yaml:` tag.

`resourceRule` being an outlier.

2024-03-15 18:51 UTC, brandtkeller approved these changes
Looks great and sets a good foundation early.

2024-03-15 20:26 UTC, mike-winberry approved these changes
Looks good!

2024-03-15 21:52 UTC, merged