feat: integrate kyverno
defenseunicorns-labs/lula1 pull request #326
Opened 2024-03-25 01:39 UTC by KhaledEmaraDev

This pull request introduces a new feature that integrates the Kyverno provider with Lula, a compliance validator. The Kyverno provider enables Lula to evaluate the domain in the target against a Rego policy.

## Key features of the Kyverno provider integration:

1. **Validation Payload:**

The validation is performed using a payload that specifies the provider (kyverno), domain (kubernetes), and the necessary configuration.
The payload includes the resource rules, Kyverno policy definition, and optional output configuration.

2. **Multiple Policy Support:**

The Kyverno provider allows defining multiple policies within the payload.
Each policy is defined using the Kyverno policy structure, including metadata, rules, and assertions.

3. **Validation Output Control:**

The `output.validation` field in the payload enables controlling which (Policy, Rule) pair determines the validation allowance or denial.
It accepts a comma-separated list of rules in the format policy-name.rule-name.

4. **Observation Output:**

The `output.observations` field in the payload allows specifying (Policy, Rule) pairs to observe violations.
Observed violations will be included in the remarks section of the relevant-evidence in the assessment results.
This integration enhances Lula's capabilities by leveraging Kyverno's policy-based validation approach. It provides flexibility in defining multiple policies, controlling validation outcomes, and observing specific rule violations.

Please refer to the provided documentation in the PR description for more details on the payload structure and usage examples.

We believe this integration will greatly benefit users who require compliance validation using Kyverno policies within the Lula framework.

2024-03-25 17:41 UTC, brandtkeller requested changes

2024-03-25 17:41 UTC, brandtkeller commented on docs/kyverno-provider.md
> +    rego: |
Copy/Paste error here - remove the rego field in favor of the current child `kyverno` field

2024-03-25 17:41 UTC, brandtkeller commented on src/pkg/providers/kyverno/kyverno.go
> +	var validation map[string]map[string]bool
This map is initialized if I understand correctly.

2024-03-25 17:41 UTC, brandtkeller commented on src/pkg/providers/kyverno/kyverno.go
> +	var observation map[string]map[string]bool
This map is initialized if I understand correctly.

2024-03-25 17:41 UTC, brandtkeller commented on src/pkg/providers/kyverno/kyverno.go
> +				matchResult.Observations[fmt.Sprintf("%s,%s-%d,%d", policy.Policy.Name, rule.Rule.Name, i, j)] = rule.Violations[0].Message
As noted on line 151 - in the event there are not violations - then this line will result in an `index out of range` error. Likely need a conditional for the success scenario. 

Additionally - this assignment will also incur an error with an uninitialized map. I would recommend creation of a temporary map to then assign to `matchResult.Observations` before returning.

2024-03-25 17:42 UTC, brandtkeller commented
@KhaledEmaraDev Appreciate the direction this is driving. If you need anything - feel free to tag me here or on the Kubernetes Slack.

2024-03-27 16:07 UTC, KhaledEmaraDev commented
Thanks @brandtkeller!

What is your opinion on the `output` field? Is the way I used it a good one: To control which policy outputs observations?

A lot of structures are OPA specific. Should we try to do a new major version and abstract theses a bit?

2024-03-27 17:35 UTC, brandtkeller commented on src/test/e2e/scenarios/pod-label/oscal-component-kyverno.yaml
> +                          ~.podsvt:
```suggestion
                          podvt:
```

2024-03-27 18:00 UTC, brandtkeller commented on src/pkg/providers/kyverno/kyverno.go
> +			validation[strings.TrimSpace(pair[0])][strings.TrimSpace(pair[1])] = true
You've initialized the map on line 107 - but I believe you'll still encounter `assignment to entry in nil map` error here due to the second map `map[string]bool` also not being initialized. Couple ways to solve this - but a conditional before this assignment should suffice.

Something like: 
```
if _, ok := validation[strings.TrimSpace(pair[0])]; !ok {
    validation[strings.TrimSpace(pair[0])] = make(map[string]bool)
}
```

2024-03-27 18:00 UTC, brandtkeller commented on src/pkg/providers/kyverno/kyverno.go
> +			observation[strings.TrimSpace(pair[0])][strings.TrimSpace(pair[1])] = true
This will incur the same issue as above for `assignment to entry in nil map`

2024-03-27 18:29 UTC, brandtkeller commented
> Thanks @brandtkeller!
> 
> What is your opinion on the `output` field? Is the way I used it a good one: To control which policy outputs observations?
> 
> A lot of structures are OPA specific. Should we try to do a new major version and abstract theses a bit?

@KhaledEmaraDev I believe the way you've implemented  `output.validation` is perfect and very configurable for optionality of 1 -> N combinations of policy/rule.

As for `output.observations` - I believe you're halfway there currently. The logic is present to map any targeted observations in the presence of violations. When there are no violations - given there is no other information to report - a generic observation that indicates "success" would more than suffice. 

Please call out anything you think we need to abstract - and we can consider/file issues. The project not reached GA currently - so we are expecting some breaking changes.

2024-03-28 03:57 UTC, brandtkeller requested changes
Added a thought for the observations. Also requesting to sign your commits as we have identified in the contributing docs. Otherwise this looks close to ready!

2024-03-28 03:57 UTC, brandtkeller commented on src/pkg/providers/kyverno/kyverno.go
> +				if len(rule.Violations) > 0 {
This is adding an observation when violations are present. Observations can also add information when successful.

Might be good to add an else here that adds a generic success response (unless there is other success data to map from the rule. 

This also might mean renaming 'observedViolations' to a more generic name.

2024-03-28 05:56 UTC, KhaledEmaraDev commented
Thanks @brandtkeller, resolved.

2024-03-28 13:59 UTC, brandtkeller commented on docs/kyverno-provider.md
> +  payload:
Missing the `resources` field with child `resource-rule`

2024-03-28 14:15 UTC, brandtkeller commented on src/pkg/providers/kyverno/kyverno.go
> +					observations[fmt.Sprintf("%s,%s-%d,%d", policy.Policy.Name, rule.Rule.Name, i, j)] = rule.Violations[0].Message
On a failing scenario where `message` was not specified in the rule - `rule.Violations[0].Message` will be an empty string I believe. 

Example failing scenario (I made foo-label-single-exists` failing
```
"labels,foo-label-exists-0,0: PASS\nlabels,foo-label-single-exists-0,1: \n"
```

Might be good practice to prepend a `FAIL` to have at a minimum a default message when the user did not include the `message` field on a rule. 

```
observations[fmt.Sprintf("%s,%s-%d,%d", policy.Policy.Name, rule.Rule.Name, i, j)] = "FAIL " + rule.Violations[0].Message
```

(or similar)

2024-03-28 15:30 UTC, mike-winberry approved these changes, later dismissed
Looks good, pending @brandtkeller requested changes.

2024-03-29 01:39 UTC, brandtkeller approved these changes
Tested a variety of permutations to work through testing the Kyverno provider. 

To include:
```
target:
          provider: kyverno
          domain: kubernetes
          payload:
            resources:
            - name: podsvt                      # Identifier for use in the rego below
              resource-rule:                     # Mandatory, resource selection criteria, at least one resource rule is required
                group:                          # empty or "" for core group
                version: v1                     # Version of resource
                resource: pods                  # Resource type
                namespaces: [validation-test]   # Namespaces to validate the above resources in. Empty or "" for all namespaces or non-namespaced resources
            - name: podvt                      # Identifier for use in the rego below
              resource-rule:                     # Mandatory, resource selection criteria, at least one resource rule is required
                name: demo-pod
                group:                          # empty or "" for core group
                version: v1                     # Version of resource
                resource: pods                  # Resource type
                namespaces: [validation-test]
            kyverno: |
              apiVersion: json.kyverno.io/v1alpha1
              kind: ValidatingPolicy
              metadata:
                name: labels
              spec:
                rules:
                - name: foo-label-exists
                  assert:
                    all:
                    - check:
                        ~.podsvt:
                          metadata:
                            labels:
                              foo: bar
                - name: foo-label-single-exists
                  assert:
                    all:
                    - message: all pods need to have label foo=bar
                      check:
                        podvt:
                          metadata:
                            labels:
                              foo: bar
            output:
              validation: labels.foo-label-single-exists,labels.foo-label-exists
              observations:
              - labels.foo-label-exists
              - labels.foo-label-single-exists
```

This all looks great!

2024-03-29 02:42 UTC, mike-winberry approved these changes

2024-03-29 02:56 UTC, merged