ADR for validation yaml
defenseunicorns-labs/lula1 pull request #354
Opened 2024-04-02 20:32 UTC by meganwolf0

This is a **really** rough first outline at what some possible options could look like for the validation yaml when we consider:
- Domain / Provider decoupling
- Remote validations
- Logical validations
- Placeholder validations

I think it might make sense to have multiple specifications for the yaml, I'm not sure if it's an anti-pattern to do a bunch of case sensitive switching on field structure, but it feels a little icky.

2024-04-02 21:21 UTC, brandtkeller commented on adr/0007-validation-yaml-format.md
> +    domain-spec:                              # Required (the spec itself can be dependent on the domain chosen, so can be flexible to new domains like infra)
What do `domain-spec` and `provider-spec` offer us logically? Looking to understand more of the intent here.

2024-04-03 00:29 UTC, meganwolf0 commented on adr/0007-validation-yaml-format.md
> +    domain-spec:                              # Required (the spec itself can be dependent on the domain chosen, so can be flexible to new domains like infra)
Did I actually screw up that part? I think for it to be valid yaml the domain and provider would be like
```yaml
domain:
  type: kubernetes
  domain-spec: ... 
```

I was just wanting some way to indicate those are the swappable pieces depending on what the domain or provider type is, for readability and for the code. I figured reusing "spec" would also be overloaded, but maybe that's fine for this. From a linting perspective I thought it would be easier to just have fully contained structures there that could be validated based on the domain/provider types.

2024-04-03 19:58 UTC, CloudBeard commented on adr/0007-validation-yaml-format.md
> +      evaluation: INTERVIEW                   # Required: INTERVIEW | EXAMINE
In the comment would it be good to call out TEST as well? That would include all 3 options. There may be cases where it could be automated once someone does a thing manually to complete a setup.

2024-04-03 19:58 UTC, meganwolf0 commented
I'm wondering if the domain.type and provider.type is redundant... that information is effectively already given in the x_spec field... so really it's more there from like a decorator perspective but in the interest of trimming fat perhaps we could do-away with it? I guess the one benefit of having it is if, for example, someone had specs for multiple providers, the "type" would point to which should actually be used. Again, perhaps not necessary though since you could probably determine logic for handling that scenario in the tool.

2024-04-03 19:59 UTC, meganwolf0 commented on adr/0007-validation-yaml-format.md
> +      evaluation: INTERVIEW                   # Required: INTERVIEW | EXAMINE
Yeah that's a good point, I can update that one

2024-04-03 20:01 UTC, CloudBeard commented
> I'm wondering if the domain.type and provider.type is redundant... that information is effectively already given in the x_spec field... so really it's more there from like a decorator perspective but in the interest of trimming fat perhaps we could do-away with it? I guess the one benefit of having it is if, for example, someone had specs for multiple providers, the "type" would point to which should actually be used. Again, perhaps not necessary though since you could probably determine logic for handling that scenario in the tool.

@meganwolf0 have you thought about when we support AWS/CSPs and Terraform etc? I think the domain/type field has more merit there. 

Also wanted to call out thatI like what you've got marked as required and optional really do line up to support other domains. Since  AWS/etc may not need that but it may need/could use others.

2024-04-03 22:15 UTC, brandtkeller commented on adr/0007-validation-yaml-format.md
> +### Proposal
Do we want to include here an additional parent element that captures defining a list of validations?

2024-04-03 22:24 UTC, brandtkeller commented on adr/0007-validation-yaml-format.md
> +Example for passthrough or placeholder validation:
This helps add some context for the `x_spec` field but may contribute to some historical confusion over time. IE if we implement passthrough/placeholder (which feels like a separate issue) but use different language or fields - search might confuse people. 

Rather i'd be more interested about potential type structures and what extending this looks like.

2024-04-04 00:42 UTC, meganwolf0 commented on adr/0007-validation-yaml-format.md
> +### Proposal
I think having the yaml documents in a single file but separated by `---` would allow them to be ingested by the yaml libs as an array of documents, so I'm not sure we need an overarching structure to contain the list of things - unless I'm missing something else about that workflow

2024-04-04 16:07 UTC, brandtkeller commented on adr/0007-validation-yaml-format.md
> +### Proposal
Just thinking about the processing piece for inclusion in a map.

In order to unmarshall a single document that contains many validations separated by `---` we'll have to parse the separate ourselves (unless that is a builtin somewhere?). 

versus having a parent element that could be unmarshalled wholesale. 


Not having a parent element would mean more alignment between `lula dev` commands and a single validation.

2024-04-05 21:14 UTC, brandtkeller commented on adr/0007-validation-artifact-format.md
> +          kind: pods                          # Required (formerly "resource" but "kind" seems to make more sense in a k8s context)
Want to open discussion here about this change `resource` -> `kind`.

Given my understanding of [resource vs kind](https://github.com/kubernetes/community/blob/7f3f3205448a8acfdff4f1ddad81364709ae9b71/contributors/devel/sig-architecture/api-conventions.md#resources) and the explicit definition of the `schema.GroupVersionResource` object that we are creating for retrieving kubernetes data dynamically - I am ensure how large of a change this would be to swap. 

Would need to dive further on the delta between `GVR` and `GVK` here - but there potentially could be support for kind without introducing any breaking change?

2024-04-09 15:55 UTC, mike-winberry requested changes

2024-04-09 15:55 UTC, mike-winberry commented on adr/0007-validation-artifact-format.md
> +  provider:
Looks good! My only thoughts are that there is some redundancy in the field names ie:
```yaml
type: opa
// We already have the type so could this just be "spec"?
opa-spec:
```
Same in the kyverno
```yaml
type: kyverno
kyverno-spec:
  kyverno:
```

Is there a way we can reduce the redundancy and more align the types since we already declare the `type: opa/kyverno`

2024-04-09 15:56 UTC, mike-winberry commented on adr/0007-validation-artifact-format.md
> +  provider:
Not really requesting changes as it isn't a major issue just wanted to highlight for discussion before we merge this and #332

2024-04-09 20:47 UTC, mike-winberry submitted a review, later dismissed

2024-04-09 21:42 UTC, brandtkeller commented on adr/0007-validation-artifact-format.md
> +          kind: pods                          # Required (formerly "resource" but "kind" seems to make more sense in a k8s context)
Discussed as a potential future investigation and feature

2024-04-09 21:52 UTC, brandtkeller commented on adr/0007-validation-artifact-format.md
> +  provider:
Discussed the complexity involved with making this changed and agreed that the current `x-spec` option provided more readability around struct use.

2024-04-09 22:03 UTC, CloudBeard approved these changes
Late to the show. Everything looks good/makes sense to me!

2024-04-09 22:21 UTC, brandtkeller approved these changes

2024-04-10 01:34 UTC, merged