Initial refactor for domains and providers
defenseunicorns-labs/lula1 pull request #358
Opened 2024-04-04 20:29 UTC by meganwolf0

Some initial stabs at refactoring the code to support domains and providers in a (hopefully) more extensible and modular way

2024-04-05 03:50 UTC, brandtkeller commented on src/pkg/common/types.go
> +// YAML data structures for ingesting validation data
Does any of this really lock us in to yaml? wondering what would need to be modified in order to support JSON and if that would change the naming here?

2024-04-05 04:05 UTC, brandtkeller commented on src/types/types.go
> +	LulaValidationTypeNormal  LulaValidationType = "Lula Validation"
let's discuss validation "types" more. Curious if that is still within the boundary of validations or not.

2024-04-05 13:10 UTC, meganwolf0 commented on src/pkg/common/types.go
> +// YAML data structures for ingesting validation data
No I think you're right, this probably shouldn't be called "yaml" - I was trying to figure out how to delineate between the pieces that would be like I/O vs the lula-internal structures (which I tried to bucket into types/types.go) but happy to rename to what makes sense there

2024-04-08 21:41 UTC, brandtkeller commented on src/pkg/providers/kyverno/types.go
> +	Kyverno *kjson.ValidatingPolicy `json:"kyverno" yaml:"kyverno"`
No change required - thinking about if `kyverno` is the most intuitive option here. 

`opa-spec` has `rego` 

Should `kyverno-spec` have `policy` ?

2024-04-08 22:11 UTC, brandtkeller requested changes
Needs `docs/` files updated.

2024-04-09 15:57 UTC, mike-winberry reviewed
Looks good, just have one item for discussion on #354

2024-04-09 20:46 UTC, mike-winberry approved these changes

2024-04-10 14:38 UTC, brandtkeller approved these changes

2024-04-10 14:40 UTC, merged