feat: Establish workflow for lula validation identifiers
defenseunicorns-labs/lula1 pull request #361
Opened 2024-04-10 16:39 UTC by brandtkeller

Closes #226 

Improving the validation identifiers to improve the developer experience and reduce potential errors due to miss identifying a link. 

## Changes 
- Provide better separation between the OSCAL and Lula validations
  - `BackMatterToMap()` now strictly provides a map[string]string object for which identified validations will then be unmarshalled and placed in the `validationMap`. 
    - This removes the need to place any identifier in the `back-matter` validation
    - This also provides a greater separation from OSCAL functionality and Lula Validation functionality
- Currently backwards compatible - this can be discussed and removed
- Establishes the use of `rel` for which we _could_ expand to include validation "types"
- `validationMap` serves future external processing - such that when an external document is unmarshalled, we can place 1 -> N validations into the map rather than having to open the same file multiple times for different validations (reuse).
- Move the unmarshall and validation of a Validation from a String (back-matter.resource[_].description) to the common package to delineate that functionality from OSCAL functionality.

2024-04-11 12:57 UTC, meganwolf0 submitted a review, later dismissed

2024-04-11 14:52 UTC, mike-winberry requested changes

2024-04-11 14:52 UTC, mike-winberry commented on src/cmd/validate/validate.go
> +	backMatterMap := oscal.BackMatterToMap(*compDef.BackMatter)
Just curious why the seperation here? is there something I am missing as to why we want to maintain two maps, rather that just eating the cost of processing the backmatter resources and getting the LulaValidations right off the bat?

2024-04-11 14:52 UTC, mike-winberry commented on src/cmd/validate/validate.go
> +	backMatterMap := oscal.BackMatterToMap(*compDef.BackMatter)
Other than that question all looks good!

2024-04-11 15:28 UTC, brandtkeller commented on src/cmd/validate/validate.go
> +	backMatterMap := oscal.BackMatterToMap(*compDef.BackMatter)
Great question and a design choice here that we can certainly dissect or revert.

Initial goal was to remove the need for any identifier in the back-matter resources. It creates additional requirements to remember and more room for error.

I see two options (maybe there are more?):
1. In the proposed logic - have the `BackMatterToMap` function simply return uuid/description (string) map for ALL back-matter resources. Then only attempt to unmarshall to a Validation object when the link contains `rel: lula`.
2. Have functionality that checks the validity of the object created and attempt to unmarshall all back-matter resources - only keeping the valid ones. 

Open to feedback.

2024-04-11 16:07 UTC, mike-winberry commented on src/cmd/validate/validate.go
> +	backMatterMap := oscal.BackMatterToMap(*compDef.BackMatter)
That makes sense! Im good. I think it can be addressed later if it needs to, I don't really see it being an issue though. Just was missing that connection between removing the id in the backmatter.

2024-04-11 16:07 UTC, mike-winberry approved these changes

2024-04-12 11:02 UTC, meganwolf0 approved these changes

2024-04-12 12:34 UTC, CloudBeard approved these changes

2024-04-12 13:00 UTC, merged