Create resources in kubernetes domain
defenseunicorns-labs/lula1 pull request #415
Opened 2024-05-14 18:42 UTC by meganwolf0

## Description

Adds an additional parameter in the Kubernetes domain spec to "create" resources. Purpose being to test admission controllers, networking, and possibly other constraints in a k8s cluster that would otherwise be challenging/impossible to evaluate simply with resource manifests.

## Related Issue

Relates to #408 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-05-18 06:03 UTC, mike-winberry commented on src/pkg/domains/kubernetes/create.go
> +	for {
This would be a good helper method to be or be a part of how we can standardize yaml parsing.

2024-05-31 17:58 UTC, meganwolf0 commented on src/pkg/domains/kubernetes/create.go
> +	for {
I couldn't really figure out how to pull this out in widely reusable function, so I created a few specific ones for the data types that might be showing up in arrays. Let me know if you see a better path forward though.

2024-06-03 21:25 UTC, mike-winberry requested changes

2024-06-03 21:25 UTC, mike-winberry commented on __debug_bin1450439560
straggle debug file?

2024-06-03 21:48 UTC, mike-winberry submitted a review, later dismissed

2024-06-05 22:12 UTC, brandtkeller requested changes
This is generating a lot of great discussion and potential. Few items I'd like to address as a team. May have even found a few unrelated bugs that need fixing.

2024-06-05 22:12 UTC, brandtkeller commented on src/cmd/validate/validate.go
> +	// Check if validations perform execution actions
I'd like to discuss the default workflow as a team and consider UX more.

It looks like Lula will check for executable validations -> If present will then prompt the user to allow executing -> if yes then validate -> if no then cancel everything.

Wanting to step back and consider UX as I see this problem on zarf all the time. "I want to do x non-interactively" and it's supported but through a combination of flags rather than the default. 

One answer may be extending the confirmation such that a user can select no executable but still perform all non-executable (via interactive options).

2024-06-05 22:12 UTC, brandtkeller commented on src/pkg/domains/kubernetes/create.go
> +	// decoder := yaml.NewYAMLOrJSONDecoder(bytes.NewReader(resourceBytes), 4096)
Clear to remove following commented code?

2024-06-05 22:12 UTC, brandtkeller commented on src/pkg/common/oscal/component.go
> +					// TODO: should this be controlID (i.e., possibly combining multiple instances of the same control?)
Want to make sure this comment was resolved? Looks like you identified correctly that `controlId` would not make a good unique identifier.

2024-06-05 22:12 UTC, brandtkeller commented on src/cmd/validate/validate.go
> +	// Create requirement store for all implemented requirements
Should this functionality move to a library in some way?

2024-06-05 22:12 UTC, brandtkeller commented on src/pkg/common/requirement-store/requirement-store.go
> +					id := common.TrimIdPrefix(link.Href)
Is this function redundant if `validation.GetLulaValidation(id)` calls it again? (or reverse)

2024-06-07 14:39 UTC, meganwolf0 commented on src/cmd/validate/validate.go
> +	// Check if validations perform execution actions
Yeah I think actually the default case is to continue executing the non-executable ones only - if you saw a different behavior then can you point me to the test file you tried with? But it might be good to make it like a few part option -> continue with non-executable or just stop. And I think yes, we probably do need to add a non-interactive flag option to at least allow this to run in a pipeline

2024-06-07 14:47 UTC, meganwolf0 commented on src/cmd/validate/validate.go
> +	// Create requirement store for all implemented requirements
Possibly... I tried to break out a lot of this to requirement-store to try and libratize(?) but there also may be a better/more encapsulated way to structure all this. The part where the comment is - on the messages to the user - feels more cli-esque so wasn't really thinking of that as a library, but perhaps some of the requirement-store functions there maybe could/should be organized differently. Idk, open to alternate thoughts on how this could look!

2024-06-07 15:02 UTC, brandtkeller commented on src/pkg/message/interactive.go
> +	confirmation := pterm.DefaultInteractiveConfirm.WithDefaultText("Do you want to continue?")
```suggestion
	confirmation := pterm.DefaultInteractiveConfirm.WithDefaultText("Do you want to run executable validations?")
```

OR similar -> current process makes me think that inputting "no" would cancel all runtime

2024-06-07 15:12 UTC, brandtkeller commented on src/cmd/validate/validate.go
> +	// Create requirement store for all implemented requirements
Resolving as I think this moves us closer. I imagine we need a library function in the future that exposes validating a component-definition in some way. From there we can resolve how to handle logging and user interaction.

2024-06-07 15:17 UTC, meganwolf0 commented on src/pkg/domains/kubernetes/create.go
> +	// decoder := yaml.NewYAMLOrJSONDecoder(bytes.NewReader(resourceBytes), 4096)
removed

2024-06-07 15:18 UTC, meganwolf0 commented on src/pkg/common/oscal/component.go
> +					// TODO: should this be controlID (i.e., possibly combining multiple instances of the same control?)
removed

2024-06-07 15:18 UTC, meganwolf0 commented on src/pkg/common/requirement-store/requirement-store.go
> +					id := common.TrimIdPrefix(link.Href)
yep I agree it's redundant, removed

2024-06-07 15:23 UTC, brandtkeller commented on src/cmd/validate/validate.go
> +	// Check if validations perform execution actions
Correct me if i am wrong here -  we cannot run validation on OSCAL containing both executable and non-executable validations in a non-interactive format when we only want the non-executable validations? (IE CI/CD)

2024-06-07 15:34 UTC, meganwolf0 commented on src/cmd/validate/validate.go
> +	// Check if validations perform execution actions
yep that's right, I think we'd need to add another flag for like non-interactive or something such that if non-interactive was flagged and confirm-execution was not, then all non-executable validations would run without prompt. That path doesn't currently exist. I held off on that because I wasn't sure if that was a path we wanted to support, but I think it should be a pretty benign addition as I already have the variable in the validation file it just would need to turn into a cmd flag

2024-06-07 15:55 UTC, brandtkeller commented on src/cmd/validate/validate.go
> +	// Check if validations perform execution actions
I see it as a necessary path - executable validations will be important on building provenance - but we'll also want defined CI workflows that only run the non-executable workflows.

2024-06-07 16:13 UTC, brandtkeller commented on src/pkg/common/validation-store/validation-store.go
> +		spinnerMessage := fmt.Sprintf("Running validation %s", k)
I believe we'll want to be more careful about our embedding of the message package in the future. Not a change required now but someone attempting to use these functions outside Lula may come knocking sooner-than-later. 

(Resolve once read)

2024-06-07 16:24 UTC, brandtkeller commented on src/pkg/common/validation-store/validation-store.go
> +			message.Debugf("Error running validation %s: %v", k, err)
Do we need some documentation that describes the output of this behavior and how it impacts the OSCAL produced? 

Current implementation will mean that any `implemented-requirement` that has both non-executable and executable validations AND is validated without the executable validations will result in the `finding` being `not-satisfied`.

I'd offer another scenario to discuss which is when we do not run executable validations - they are ignored and do not impact the findings.

IE I expect executable validations to be run against dev/test/staging environments BUT when promoted to production I still want to evaluate my assessment results without executable validations. 

we don't have any real data to support what people would optimally want here - but I err on the side of caution.

2024-06-10 15:51 UTC, meganwolf0 commented on src/pkg/common/validation-store/validation-store.go
> +			message.Debugf("Error running validation %s: %v", k, err)
Yeah, I think this is probably feeding into a larger conversation about when to mark something satisfied / not-satisfied. If I think back to the whole placeholder discussion - I see the non-execution of these policies as turning into default, not-satisfied placeholders such that a user would want to manually evaluate the specific aspect for satisfaction. And by keeping it not-satisfied we're basically telling the user/reviewer there's more work to be done. I suppose I'm being more conservative in just making things not-satisfied but would be interested in the best approach from a larger compliance and reporting standpoint.

I will include additional documentation on this - all the validations will default to `not-satisfied` if they can't be evaluated so a) yes good to outline that and b) probably good to have an internal conversation on if we want to modify that decision in general. Since we only have a binary decision, I would think we shouldn't default to `satisfied` but instead add a third option such as `not-evaluated` or something if we want the distinction.

2024-06-10 17:16 UTC, meganwolf0 commented on src/pkg/common/validation-store/validation-store.go
> +			message.Debugf("Error running validation %s: %v", k, err)
added `docs/assessment-results.md` to try and address. I realized we don't have any documentation on Lula <> OSCAL artifacts (short of the ADRs), maybe we need to add an issue for that if appropriate?

2024-06-11 15:14 UTC, brandtkeller commented on src/pkg/common/validation-store/validation-store.go
> +			message.Debugf("Error running validation %s: %v", k, err)
I can appreciate being conservative here. I'm trying to project "How would this work in Production" and I may be very wrong. 

I hold an _assumption_ that we want to report on all non-executable validations while still understanding and reporting controls of-which all other validations pass. I am concerned we'll dilute the results in efforts of being conservative to the point where everything will still report `not-satisfied` given some extenuating circumstance. 

This is a tough one...

2024-06-11 18:13 UTC, CloudBeard commented on src/pkg/common/validation-store/validation-store.go
> +			message.Debugf("Error running validation %s: %v", k, err)
Would the reason field of other make better sense for the not-evaluated ?

https://pages.nist.gov/OSCAL-Reference/models/v1.1.2/assessment-results/json-reference/#/assessment-results/results/findings/target/status/reason

I think assessors will look at it more cut and dry but I do see the need to call out that they didn't pass because there wasn't anything to pass/test against. Both internally so you know the difference in it didn't pass becuase we don't have a test and the opposite that. That would give a way to pull relative the needed info out for the why but still show its not met?

2024-06-11 18:28 UTC, mike-winberry commented on src/pkg/common/validation-store/validation-store.go
> +			message.Debugf("Error running validation %s: %v", k, err)
After reading through the oscal docs, I agree with @CloudBeard that we could establish our own "reason" or use the "other" as one of the "defaults" OSCAL recommends, but it can be anything, I would also probably lean toward the not satisfied, but theres in interesting use case for when it is all satisfied in the dev env, and how those two link up.

2024-06-11 19:06 UTC, mike-winberry commented on src/pkg/common/validation-store/validation-store.go
> +			message.Debugf("Error running validation %s: %v", k, err)
I also think we are limited to `satisfied` `not-satisfied` based on [state](https://pages.nist.gov/OSCAL-Reference/models/v1.1.2/assessment-results/json-reference/#/assessment-results/results/findings/target/status/state)
>The value must be one of the following:
> - satisfied: The objective has been completely satisfied.
> - not-satisfied: The objective has not been completely satisfied, but may be partially satisfied.

2024-06-12 20:43 UTC, brandtkeller commented on src/pkg/common/validation-store/validation-store.go
> +			message.Debugf("Error running validation %s: %v", k, err)
Created #478 to capture the intent of this larger discussion. Resolving this thread.

2024-06-12 21:18 UTC, brandtkeller submitted a review, later dismissed

2024-06-13 18:26 UTC, brandtkeller approved these changes

2024-06-15 03:14 UTC, mike-winberry approved these changes

2024-06-17 10:13 UTC, merged