feat: add looping for lint
defenseunicorns-labs/lula1 pull request #481
Opened 2024-06-13 01:37 UTC by CloudBeard

## Description

Adds loop for lula lint.

Removed mention of yaml to future proof for xml (sorry for anyone reading that manually) and json.

Changed wording around single files to multiple files.

## Related Issue

Fixes: https://github.com/defenseunicorns/lula/issues/480 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-06-13 03:06 UTC, brandtkeller requested changes
Great first pass - I have a few modifications we should consider: 

This will fail on the first document that fails linting and exit - optimally the workflow would lint all files and report on which are passing AND failing in some capacity. This prevents the cycle of fixing one file at a time. 

This could be iterating through the loop as implemented - identifying pass/fail with some information and once all files have been evaluated then indicating overall success/failure. 

Looking to prevent scope creep here - I do not believe:
```
validation.WriteValidationResult(validationResp.Result, opts.ResultFile)
```
 will handle appending to a result file (currently intended for a single write operation). Meaning we need to update the go-oscal function or develop a stop-gap in the interim. 
 
 Focus on the core logic - will evaluate go-oscal

Open to feedback

2024-06-14 20:22 UTC, brandtkeller requested changes

2024-06-14 20:22 UTC, brandtkeller commented on src/cmd/tools/lint.go
> +					message.Fatalf(err, "Failed to write validation results to %s\n", opts.ResultFile)
```suggestion
					message.Fatalf(err, "Failed to write validation results to %s with error: %s", opts.ResultFile, err.Error())
```

This adds more context around why the error happened -IE if I supplied `-r output.xml` it will tell me that it failed to write AND that the file type can only be yaml or json.

2024-06-14 20:22 UTC, brandtkeller commented on src/cmd/tools/lint.go
> +					continue
The presence of this `continue` will prevent the `ValidationResult` from being appended below and as such the failed results will not be present in the output file. 

Given there may be a number of errors that could have been returned from the function -> I would: 
- attempt to catch known errors for failed linting (or otherwise halt execution with a fatal log)
- proceed to still log warnings as done below (no modification needed)
- proceed to add all results to the slice as done below (no modification needed)
- and then add a conditional at the end with `validationResp.Result.Valid` logging success - else logging failed linting

2024-06-15 03:34 UTC, mike-winberry reviewed
Agree with @brandtkeller's changes, nothing else stood out me!

2024-06-17 19:53 UTC, brandtkeller commented on src/cmd/tools/lint.go
> +					if validatorErr, ok := err.(wrappedValidatorError); ok {
Can you point us to where this originates?

2024-06-17 20:01 UTC, CloudBeard commented on src/cmd/tools/lint.go
> +					if validatorErr, ok := err.(wrappedValidatorError); ok {
From local testing of a wrapper. It worked having a wrapper so I could have assertions on validation.ValidationError to check for the know error types in the validationError.

I may also be going down the wrong path to solve for: attempt to catch known errors for failed linting (or otherwise halt execution with a fatal log)

So in go-oscal validationError.go the wrapper would be 

```go
func (e ValidatorError) Error() string {
	return e.Error
}
```

In lint.go id swap that a bit wording wise to 

```go
if err != nil {
    if validatorErr, ok := err.(validation.ValidatorError); ok {
        message.Fatalf(err, "Validation error occurred while linting %s: %v\n", inputFile, validatorErr)
    } else {
        message.Warnf("Failed to lint %s: %v\n", inputFile, err)
        errorsOccurred = true
    }
}
```

2024-06-17 20:53 UTC, mike-winberry commented
- [ ] depends on https://github.com/defenseunicorns/go-oscal/issues/266

2024-06-19 04:53 UTC, mike-winberry commented
- [ ] depends on #492

2024-06-27 02:00 UTC, mike-winberry approved these changes

2024-06-27 02:05 UTC, mike-winberry requested changes

2024-06-27 02:05 UTC, mike-winberry commented on src/cmd/tools/lint.go
> +				if opts.ResultFile != "" {
Do we want to extract the results into a slice and the use `validation.WriteResult` if `len == 1` else `validation.WriteResults` (added in go-oscal v0.5.0)?

2024-06-27 02:15 UTC, mike-winberry commented on src/cmd/tools/lint.go
> +				if opts.ResultFile != "" {
https://github.com/defenseunicorns/lula/pull/504

2024-06-27 13:56 UTC, mike-winberry approved these changes

2024-06-28 21:56 UTC, brandtkeller approved these changes
Operating as expected - walked through a few workflows and received intended results.

2024-06-28 22:03 UTC, merged