fix(oscal): single model write operations support
defenseunicorns-labs/lula1 pull request #502
Opened 2024-06-25 18:56 UTC by brandtkeller

## Description

Only allow a single model per file write - validate that is the case

## Related Issue

Fixes #501

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-06-26 17:32 UTC, mike-winberry requested changes

2024-06-26 17:32 UTC, mike-winberry commented on src/pkg/common/oscal/complete-schema.go
> +	// Check if one model present and all other nil - is there a better way to do this?
Performance wise, I think this is probably the best, the only other things I can think of are reflection, map conversion, (un)marshalling all of which may be pointlessly complex and slow rn. Though this could lead to needed maintenance that could be avoided with those options...Looking at WriteOscalModel, it may be possible to re-arrange the order of ops, to save that performance hit, since we will be writing and converting back to bytes, so it would only be one additional marshal to convert to a map and then remove the need for the hardcoded strings (will be in json/yaml form) and may remove the need for the hardcoded checks. May be worth an issue.

2024-06-26 17:43 UTC, mike-winberry commented on src/pkg/common/oscal/complete-schema.go
> +	// Check if one model present and all other nil - is there a better way to do this?
#503

2024-06-26 17:44 UTC, mike-winberry approved these changes

2024-06-27 20:58 UTC, CloudBeard approved these changes

2024-06-28 22:12 UTC, brandtkeller commented on src/pkg/common/oscal/complete-schema.go
> +	// Check if one model present and all other nil - is there a better way to do this?
agreed! Considered other options but kept coming back to the same complexity for the same problem. Kept this one readable (albeit verbose) for traceability. Appreciate the issue.

2024-06-28 22:43 UTC, merged