feat: initial-ssp-generate-doc
defenseunicorns-labs/lula1 pull request #548
Opened 2024-07-22 17:52 UTC by CloudBeard

## Description

This ssp generate document also has a digram in Miro that helps illustrate the depency graph.

! Due to the size of OSCAL Models including a Mermaid diagram is illegible.

This doc outlines the elements contained within the component-definition and profile that help fill out the ssp. 

It also contains the items that are needed through a config file and the elements that need augmented within the component-definition.

## Related Issue

Relates to https://github.com/orgs/defenseunicorns/projects/12/views/5?pane=issue&itemId=54551768

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-07-22 19:20 UTC, brandtkeller commented
For posterity - discussed splitting the content into `docs/oscal/system-security-plan.md` for content relating to the model generically and `cli-commands/generate/system-security-plan.md` for the logical implementation documentation.

2024-07-25 02:44 UTC, brandtkeller requested changes
Would like to generalize some of the content to remove mention of topics that still have a large amount of discovery to perform. 

These docs will go live on our docs site upon renovate merge to the `lula-docs` repo - we should be explicit in defining the `generation` document as proposed work and not yet implemented.

2024-07-25 02:44 UTC, brandtkeller commented on docs/cli-commands/generation/system-security-plan.md
> +# System Security Plan
All docs in theory will be published to our website. I would request a note of some type at the top of this document to mention that this is proposed work captured for research purposes.

2024-07-25 02:44 UTC, brandtkeller commented on docs/cli-commands/generation/system-security-plan.md
> +- The output file of the component `-o` or `--output`; `oscal-component.yaml`
`output` would be an ssp not component yes?

2024-07-25 02:44 UTC, brandtkeller commented on docs/cli-commands/generation/system-security-plan.md
> +For the items in `Elements in SSP Not in Component Definition` a "config" file will be needed to fill in the gaps. There are also metadata fields such as `responsible-roles`, `responsible-parties`, a
We need to generalize more before we can definitively say what the path forward will be. IE "context will be needed to fill in the gaps as well as establish common data across models".

2024-07-25 02:44 UTC, brandtkeller commented on docs/cli-commands/generation/system-security-plan.md
> +### Elements in Component Definition Not in SSP
Of the categories below - am I missing "Applicable fields in Component Definition that translate to an SSP" somewhere?

2024-07-25 02:44 UTC, brandtkeller commented on docs/oscal/system-security-plan.md
> +A [System Security Plan](https://pages.nist.gov/OSCAL-Reference/models/v1.1.2/system-security-plan/json-reference/#/system-security-plan) is an OSCAL-specific model to represent a system as a whole.
Let's drop mention of `LulaOscalConfig` - we know we want to implement generate functionality - but templating and variables is still a research topic.

2024-07-30 20:19 UTC, meganwolf0 commented on docs/cli-commands/generation/system-security-plan.md
> +# System Security Plan
So I think with that header, the menu item will be "**NOTE:** This Document is in an active research phase." - wondering if instead we might want like a future or proposed or something directory? Also, wondering if we did like a .dir if that would be hidden from rendering in the website... possibly a question to @bdfinst

2024-07-31 02:05 UTC, brandtkeller commented on docs/cli-commands/generation/system-security-plan.md
> +# System Security Plan
agree on moving the `note` below the main H1 at a minimum. 

Open to thoughts on future content. I like the idea of ensuring they get exposed in our repo/website. We may be constrained by the amount of features we can develop currently - but getting general intent published will hopefully go a long way by generating some demand signals.

2024-08-09 15:58 UTC, meganwolf0 approved these changes, later dismissed

2024-08-09 20:39 UTC, brandtkeller commented on docs/oscal/assessment-results.md
> +- Back Matter Resources are sorted by `title` in ascending order.
Why are there duplicates of this line item?

2024-08-09 21:27 UTC, brandtkeller approved these changes

2024-08-09 21:31 UTC, merged