refactor(tests): 586 refactor unhappy path e2e tests
defenseunicorns-labs/lula1 pull request #598
Opened 2024-08-14 14:24 UTC by meganwolf0

## Description

Overall intent is to make sure all "unhappy path" testing is done for the validations and `lula dev validate`. Much of this is caught by the schema, some of it is not. Added tests for individual domains/providers assuming they can be consumed in absence of schema validation methods. The following is a list of updates/additions, working from the most narrow-scope upward:

- Updated functionality in each domain and provider to create/validate the spec structure and return errors if invalid + unit tests to exhaustively document valid/invalid cases for each
- Updated GetDomain and GetProvider testing to for error handling/evaluation
- Added common/types testing for ToLulaValidation to check for all error types 
  -> Required updated schema -> opa-spec.output.observations is allowed to be nil
- Added unhappy path tests for composition unit and e2e tests, this was pulled out of the `src/test/e2e/scenarios/pod-label/oscal-component-all-bad.yaml`
- Updated `pod_validation_test.go` to map the expected error type to the specific observation failure

## Related Issue

Fixes #586 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (addresses tech debt in testing, slight schema modification)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-08-18 14:56 UTC, brandtkeller requested changes
Minor questions and typos otherwise I very much appreciate this baseine.

2024-08-18 14:56 UTC, brandtkeller commented on src/pkg/common/composition/composition_test.go
> +	t.Run("No imports, local validations, bad href", func(t *testing.T) {
These two new tests are just happy path tests with known bad conditions?

2024-08-18 14:56 UTC, brandtkeller commented on src/pkg/common/types_test.go
> +			name: "Invalid provider scheam, bad type",
```suggestion
			name: "Invalid provider schema, bad type",
```

2024-08-18 14:56 UTC, brandtkeller commented on src/pkg/common/types_test.go
> +			name: "Invalid provider scheam, missing spec",
```suggestion
			name: "Invalid provider schema, missing spec",
```

2024-08-18 14:56 UTC, brandtkeller commented on src/pkg/domains/kubernetes/types.go
> +		return nil, fmt.Errorf("resources, create-resources, or wait must be specified")
```suggestion
		return nil, fmt.Errorf("one of resources, create-resources, or wait must be specified")
```

2024-08-19 13:02 UTC, meganwolf0 commented on src/pkg/common/composition/composition_test.go
> +	t.Run("No imports, local validations, bad href", func(t *testing.T) {
Yeah exactly - I had some bad href values in the `src/test/e2e/scenarios/pod-label/oscal-component-all-bad.yaml` that I felt should be over here

2024-08-19 20:20 UTC, brandtkeller commented on src/pkg/common/composition/composition_test.go
> +	t.Run("No imports, local validations, bad href", func(t *testing.T) {
And to clarify - the purpose of these tests is to ensure these scenarios do not return any errors?  Should they be returning errors given the bad inputs?

2024-08-20 14:42 UTC, meganwolf0 commented on src/pkg/common/composition/composition_test.go
> +	t.Run("No imports, local validations, bad href", func(t *testing.T) {
I think it's supposed to be composing cleanly - i.e., no errors... I think that's sort of how we've been operating such that those errors get raised up on validate (in the remarks), instead of err-ing during compose... so I think the result of this test tracks with how we've been using this function, idk if we want to revisit that though

2024-08-20 15:02 UTC, brandtkeller commented on src/pkg/common/composition/composition_test.go
> +	t.Run("No imports, local validations, bad href", func(t *testing.T) {
Fair!

2024-08-20 15:03 UTC, brandtkeller approved these changes

2024-08-20 15:20 UTC, merged