Initial lula report
defenseunicorns-labs/lula1 pull request #599
Opened 2024-08-14 14:30 UTC by CloudBeard

# STILL WIP

## Description

Adds report functionality starting with component definition.

Will report how many controls are mapped per source and per framework for each component. There is the possibility that a component-definition file has multiple sources and multiple frameworks. The current report will list how many controls are in each and will give a % mapped based on the source provided for each.

## Related Issue

Relates to #223 and #247 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-08-14 15:43 UTC, brandtkeller commented
Quick feedback loop - I can trace the code but I would always recommend starting with docs on a new feature. 

Capture the purpose - let people challenge that intent. 

I don't believe this needs an ADR - so docs would be sufficient. 

At the same time I think we should keep challenging if we know enough to pursue it further. Does this provide enough value to be of use or does some infrastructure require more maturation first. Transparently I do not know if we have enough context to make the result meaningful.

2024-08-20 03:17 UTC, CloudBeard commented
Still need to add tests but want to figure out where/what packages to create to tidy up the main report code.

2024-08-28 23:36 UTC, brandtkeller requested changes
Trending in the right direction now that we're getting to core of what we need (or can provide currently). 

I think we're still missing a bit of big picture vision -> Which I/the team can help define. 

See my comment about the context that drives the reporting (as we see it today). Ideally we as a team need to provide a clearer deliverable on our issues (WIP) - but I appreciate you pursuing this nonetheless. 

My current take:
Reporting should be a function of collecting available context and reporting accordingly. 
- First iteration starts with component-definition and reports controls available. 
- With the presence of a catalog/profile -> we can overlay that control information to calculate percentages. 
- with the presence of assessment-results we can check satisfied/not-satisfied 

Given that - we can start migrating functionality to the oscal model libraries for each model as applicable to get the context we need to return here for collective reporting. 

My  opinion is that reporting is not singly-model focused and rather total context driven. I may be very wrong - let's chat as a team if anyone feels otherwise.

2024-08-28 23:36 UTC, brandtkeller commented on src/cmd/report/report.go
> +		if opts.InputFile == "" {
If we mark this flag as [required](https://github.com/spf13/cobra/blob/main/site/content/user_guide.md#required-flags) then we can remove this check

2024-08-28 23:36 UTC, brandtkeller commented on src/cmd/report/report.go
> +var reportHelp = `
Capture the full intent of what this command will perform here (different options etc). Later doc generation (prior to review) will recreate the docs above.

2024-08-28 23:36 UTC, brandtkeller commented on src/cmd/report/report.go
> +		modelType, err := determineOSCALModel(oscalModels)
This may be a good spot to establish a separation of duties -> We've performed the essential operation of retrieving/parsing the data -> now let's create a function that handles the next steps.

2024-08-28 23:36 UTC, brandtkeller commented on src/cmd/report/report.go
> +		spinner = message.NewProgressSpinner("Generating report")
I don't believe the intent of this operation is going to be an OR but rather an AND in the long term. Can we possibly re-orient functionality to process the context that is present? (focusing on component-definitions here)

2024-09-18 22:02 UTC, CloudBeard commented on src/cmd/report/report.go
> +		if opts.InputFile == "" {
Swapped that to required removed the check.

2024-09-18 22:03 UTC, CloudBeard commented on src/cmd/report/report.go
> +var reportHelp = `
Added more data/examples in the help

2024-09-18 22:04 UTC, CloudBeard commented on src/cmd/report/report.go
> +		modelType, err := determineOSCALModel(oscalModels)
I ended up splitting that up twice, the first time just to separate duties but ended up adding 2 new functions. 1 that is public that will run the actual logic and the second that is a handler for model handlers.

Ran into an issue testing so I came back to add the function that runs the logic.

2024-09-18 22:12 UTC, CloudBeard commented on src/cmd/report/report.go
> +		spinner = message.NewProgressSpinner("Generating report")
I agree but not 100% sure I implemented this part. 

Long term if we run `lula report -f assessment-results.yaml` and we have an OSCAL model for all models then the SAR imports the SAP, SAP imports the SSP, and the SSP imports the Components so we'd have a lot of data to pull from. Ive also thought about locality of the OSCAL.

Short term/this PR im not sure what else to pull out from just the component definitions until we have profile/catalog support. I can see some more there but can be added to. I was thinking new handler per model that can call X functions to do logic work on that model. Also reach across handlers to intertwined models.

Near example would be when we have that profile and catalog support in fully, report on component definition will give you data around the catalog/profile too but use their handlers/functions.

2024-09-19 22:55 UTC, brandtkeller requested changes
No issues with the current direction. 

I would remove the current documentation and run a `lula internal gen-cli-docs` in order to generate the new CLI docs for this command. Iterate as necessary to try and capture all context in the CLI command code as possible. If you need additional docs place them outside the `docs/cli-commands` directory. 

Otherwise this gets us moving in the right direction - as I mentioned previously, I expect future iterations to be less of a model-by-model reporting structure and rather wholistic reporting of all models - but that is out of scope currently.

2024-09-19 22:55 UTC, brandtkeller commented on src/cmd/report/report.go
> +	modelType, err := determineOSCALModel(oscalModels)
The `oscal` pkg under `src/pkg/common/oscal` contains a `GetOscalModel()` that returns the same values. 

I would consider removing this -> removing the required parameter from the `handleOSCALModel()` function and call it directly inside `handleOSCALModel()`. 

Unless you have some unique requirement.

2024-09-19 22:55 UTC, brandtkeller commented on src/test/e2e/report_test.go
> +func TestReportCommand(t *testing.T) {
Any reason these cannot serve as more of a unit test to be coupled with the `report` package. 

I'd like to start iterating `E2E` tests to be more CLI-driven context.

2024-09-19 22:55 UTC, brandtkeller commented on src/test/e2e/report_test.go
> +            name:       "Catalog OSCAL Model",
in addition to the conversion of this test to more of a unit test -> it may help reduce testing file requirements. Possible use of data structures and objects if possible (look at your function inputs/outputs and consider the requirements).

2024-09-19 22:55 UTC, brandtkeller commented on src/cmd/report/report.go
> +func handleComponentDefinition(componentDefinition *oscalTypes_1_1_2.ComponentDefinition, format string) error {
Should we consider composing comp-defs here prior to processing?

2024-09-19 23:00 UTC, brandtkeller commented on src/cmd/report/report.go
> +		spinner = message.NewProgressSpinner("Generating report")
I believe we have a common vision here - but we are blocked by other circumstances so I'm good with pressing in the current direction and evolving this design over time,

2024-09-30 20:25 UTC, CloudBeard commented on src/cmd/report/report.go
> +	modelType, err := determineOSCALModel(oscalModels)
I ended up using a few more functions from common where I found redundancy.

2024-09-30 20:25 UTC, CloudBeard commented on src/test/e2e/report_test.go
> +func TestReportCommand(t *testing.T) {
Swapped those to unit and I think created a more CLI approach.

2024-09-30 20:26 UTC, CloudBeard commented on src/test/e2e/report_test.go
> +            name:       "Catalog OSCAL Model",
Created a mock component definition data structure to have some data for testing.

2024-09-30 20:27 UTC, CloudBeard commented on src/cmd/report/report.go
> +func handleComponentDefinition(componentDefinition *oscalTypes_1_1_2.ComponentDefinition, format string) error {
Good call! added the compose pieces to the beginning there.

2024-09-30 21:42 UTC, brandtkeller requested changes

2024-09-30 21:42 UTC, brandtkeller commented on src/cmd/report/report.go
> +	Short:   "Build a compliance report",
Let's challenge this a bit more -> what function does or can this command serve?

> Report on the current state of compliance
or....

2024-09-30 21:42 UTC, brandtkeller commented on src/cmd/report/report.go
> +var reportCmd = &cobra.Command{
I know this has been up for some time - Can we align the creation of this command to `template` such that the same cobra patterns are followed?

2024-09-30 21:42 UTC, brandtkeller commented on src/cmd/report/report.go
> +package report
Formatting appears non-standardized across this file (maybe others). 

I'd run a `go fmt src/cmd/report/report.go` to resolve the formatting and review other modified files. This can also be configured in your development environment whenever "saving".

2024-09-30 21:42 UTC, brandtkeller commented on src/test/e2e/report_test.go
> +func TestLulaReportValidComponent(t *testing.T) {
Heading in the right direction. We have some examples and test utilities to pull from. Would like to standardize on that and @meganwolf0 may have some insights for what we need for structure.

2024-10-01 14:17 UTC, CloudBeard commented on src/cmd/report/report.go
> +	Short:   "Build a compliance report",
Maybe not build a compliance report as in a pdf but I can see it pulling various statics and data out of the OSCAL to be easier to read and understand. I am picturing a thousands of lines SSP and I want to know what controls am I missing, what controls do I have, do I have multiple frameworks and can I see that per framework. For POAMs Im thinking how do I see my critical or highs specifically, how do I see time left on moderates to patch. 

For components I would like to have a quick count of controls per framework, how many have validations, how many controls are in this component-definition that aren't in a profile/catalog. 

I can also see parts of it being reused similar to `lula evaluate -f assessment-result.yaml --sumnmary` doing the summary part. 

Maybe the part that gets the data for UDS Runtime to present too. Thought there is it would be similar questions/data points around the OSCAL to show.

2024-10-02 13:44 UTC, meganwolf0 commented on src/cmd/report/report.go
> +func PrintReport(data ReportData, format string) error {
Haven't picked through this, so this function might not be relevant, but the `Table` under [messages](https://github.com/defenseunicorns/lula/blob/1ab0eefdeeb1d59f16f33249b1a6fce141ef5942/src/pkg/message/message.go#L322) might save some of this functionality

2024-10-02 13:47 UTC, meganwolf0 commented on src/test/e2e/report_test.go
> +func TestLulaReportValidComponent(t *testing.T) {
Looks like this might be in reference to doing some golden file checks, I think the [PR for compose](https://github.com/defenseunicorns/lula/pull/686/files#diff-1a3ee14400dbe38c385f9e2c566a655860814625b79fd3b6dd831a9e2d275c8a) should provide some reusable functions for checking the data from report, and the `tools_compose_test.go` and `tools_template_test.go` might be decent-ish places to start from

2024-10-02 13:47 UTC, meganwolf0 commented on src/test/e2e/report_test.go
> +func TestLulaReportValidComponent(t *testing.T) {
(I think there was also a discussion we were going to have as a team about e2e testing practices/structure so some of that could change)

2024-10-03 16:06 UTC, CloudBeard commented on src/cmd/report/report.go
> +var reportCmd = &cobra.Command{
Believe ive restructured this

2024-10-03 16:07 UTC, CloudBeard commented on src/cmd/report/report.go
> +package report
Just ran this and updated my settings in VScode for futures.

2024-10-10 16:26 UTC, CloudBeard commented on src/cmd/report/report.go
> +func PrintReport(data ReportData, format string) error {
I added that table functionality, I like the way that looks.

2024-10-10 16:26 UTC, CloudBeard commented on src/test/e2e/report_test.go
> +func TestLulaReportValidComponent(t *testing.T) {
I believe ive followed the same structure

2024-10-11 13:09 UTC, meganwolf0 commented
Just tested locally - is this `il4` supposed to be down in the framework table?
![CleanShot 2024-10-11 at 09 07 58](https://github.com/user-attachments/assets/dca6980e-7eaf-44fd-b7f2-07148d0cf5f0)

2024-10-11 16:19 UTC, CloudBeard commented
> Just tested locally - is this `il4` supposed to be down in the framework table? ![CleanShot 2024-10-11 at 09 07 58](https://private-user-images.githubusercontent.com/97549300/375764865-dca6980e-7eaf-44fd-b7f2-07148d0cf5f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjM4NjAsIm5iZiI6MTcyODY2MzU2MCwicGF0aCI6Ii85NzU0OTMwMC8zNzU3NjQ4NjUtZGNhNjk4MGUtN2VhZi00NGZkLWI3ZjItMDcxNDhkMGNmNWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE2MTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNmFkNDEwYTdmYmRlN2U4MmMyNjVkMWIyODdiODEzMWFlNzRjZmY0NDQzNmVhNDZhYmE3OGViMjdiODRiZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F2aqpa7ApAIOW3iNa06GtGoJgBCmDevt8aMgERDMEJ4)

Yea that would make sense. Ill fix that real quick-ish

2024-10-11 17:59 UTC, brandtkeller requested changes

2024-10-11 17:59 UTC, brandtkeller commented on src/internal/reporting/helpers.go
> +func fetchOrReadFile(source string) ([]byte, error) {
`network.Fetch()` will return file bytes for local files on the filesystem or remote files on network. I don't believe this functionality is needed unless you have an edge case you're solving for.

2024-10-11 17:59 UTC, brandtkeller commented on src/internal/reporting/helpers.go
> +func isURL(str string) bool {
Given the comment below I imagine this will be removed - but I do think this has some gaps worth addressing if it were to be kept. 

IE the return statement does not indicate a value that aligns to the function intent.

2024-12-05 04:46 UTC, brandtkeller requested changes

2024-12-05 04:46 UTC, brandtkeller commented on src/cmd/report/report.go
> +		message.Fatal(err, "error initializing upgrade command flags")
```suggestion
		message.Fatal(err, "error initializing report command flags")
```

2024-12-05 04:46 UTC, brandtkeller commented on src/test/e2e/report_test.go
> +func TestLulaReportValidComponent(t *testing.T) {
Is this file still required given `cmd_report_test.go`?

2024-12-09 22:43 UTC, brandtkeller requested changes
I believe you might have removed the wrong test. 

`src/test/e2e/repor_test.go` feels redundant while the test that was in `src/internal/reporting` might still be valid.

2024-12-19 03:25 UTC, brandtkeller approved these changes
Appreciative of you running point here and exposing this as an area of importance for users to give us feedback on.

2024-12-19 03:25 UTC, merged