Tui experimentation
defenseunicorns-labs/lula1 pull request #608
Opened 2024-08-19 12:33 UTC by meganwolf0

## Description

Initial TUI Experimentation for read-only operations on component-defn OSCAL model

## Related Issue

Fixes #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-08-20 14:33 UTC, meganwolf0 commented
Looking for a review on the read-only component-definition features, still need to add some docs - any thought as to where those should go?

2024-08-21 16:38 UTC, brandtkeller requested changes
Appreciative of functionality that thinks about the OSCAL as more than just the scope of NIST 800-53.

2024-08-21 16:38 UTC, brandtkeller commented on src/cmd/tui/tui.go
> +	lula tui /path/to/oscal-component.yaml
Given the `Fatal` message item below when a file is not specified - can we update the command to include the standard `-f / --input-file` flag and mark it as required? Removes the need for that argument check ,improves native cobra flow and should provide more input validation.

2024-08-26 15:27 UTC, meganwolf0 commented
> Removes the need for that argument check ,improves native cobra flow and should provide more input validation.

So I was thinking about this more and wondering if that truly is more "native cobra" - as the Run command expects `args` and this will not run without that argument, so I'm wondering why is it bad to have that check (`len(args)==0`) ? I agree that it's more aligned with our other usage of flags, but also wondering if we should think more about the conventions we've set up for ourselves. If we are constantly having to put -f for a completely mandatory input, is that really desirable? Should flags be more in the realm of optional or intended to have alternative behaviors or additional functionality, as opposed to enforcing mandatory fields (e.g., file inputs)...

Anyway, I can change this, it's more just a thought about why/when to use flags vs args.

2024-08-26 20:19 UTC, CloudBeard commented on src/internal/tui/component/component.go
> +					m.selectedControl = m.controls.SelectedItem().(control)
Does something like  `if selectedControl := m.selectedControl.SelectedItem().(control) != nil` to check if the thing you're searching for in the control is there to prevent crashes?

2024-08-26 20:20 UTC, CloudBeard commented on src/internal/tui/component/component.go
> +					m.selectedControl = m.controls.SelectedItem().(control)
Similar to line 288 is what im basing it on.

2024-08-26 20:20 UTC, CloudBeard commented
Finally got hands on with the TUI and its so cool, big fan.

I feel like the -f starts to fall into the log/stdout usage area.

2024-08-26 20:33 UTC, meganwolf0 commented on src/internal/tui/component/component.go
> +					m.selectedControl = m.controls.SelectedItem().(control)
Not sure I'm 100% following, but I believe you don't need to check the filter since that's handled by the bubbles/list model.
This portion
```go
if selectedItem := m.validations.SelectedItem(); selectedItem != nil {
  m.selectedValidation = selectedItem.(validationLink)
}
```
was implemented because you could hit a case where the controls have no validations linked, so those cases the "selectedItem" would be nil.

If you are poking at the case where there's no implemented requirements (e.g., controls) - I just tried importing a file with that as empty and the oscal linting seems to block it... so idk if that's invalid oscal?

2024-08-27 15:01 UTC, CloudBeard commented on src/internal/tui/component/component.go
> +					m.selectedControl = m.controls.SelectedItem().(control)
OOO So what I was doing was typing this into the filter on Controls List and I noticed if it wasn't in the control text and I hit enter it would crash

![image](https://github.com/user-attachments/assets/817f2a35-87b3-4b33-a07b-31de08fe015e)

![image](https://github.com/user-attachments/assets/34687f47-c8fa-4882-9f22-707cbb178634)


This dosen't happen in the validations section I think becuase of 

```go
if selectedItem := m.validations.SelectedItem(); selectedItem != nil {
  m.selectedValidation = selectedItem.(validationLink)
}
```

2024-08-27 20:27 UTC, meganwolf0 commented on src/internal/tui/component/component.go
> +					m.selectedControl = m.controls.SelectedItem().(control)
Ah ok thanks for finding that case - I'll update this!

2024-08-28 15:27 UTC, brandtkeller commented
Is there any common testing patterns for this model of TUI? 

Open to making that a separate deliverable but I imagine we will begin hitting many edge cases where a separation of how the model is visualized is separate from unit testing functions.

2024-08-28 15:55 UTC, meganwolf0 commented
> Is there any common testing patterns for this model of TUI?

hmmm maybe we could look at adding VHS for testing - might need a human to review the gifs but possibly better than nothing? Looks like this [teatest](https://pkg.go.dev/github.com/charmbracelet/x/exp/teatest) library kind of exists, but the fine print on the repo doesn't guarantee any backward compatibility or future support...

2024-08-28 16:25 UTC, brandtkeller commented
> > Is there any common testing patterns for this model of TUI?
> 
> hmmm maybe we could look at adding VHS for testing - might need a human to review the gifs but possibly better than nothing? Looks like this [teatest](https://pkg.go.dev/github.com/charmbracelet/x/exp/teatest) library kind of exists, but the fine print on the repo doesn't guarantee any backward compatibility or future support...

I'd lean towards TeaTest given that we manage that dependency accordingly. I'd like to review capabilities (again maybe a separate issue) and annotate gaps -> maybe there is room to contribute back.

2024-08-28 19:20 UTC, meganwolf0 commented
> I'd lean towards TeaTest given that we manage that dependency accordingly. I'd like to review capabilities (again maybe a separate issue) and annotate gaps -> maybe there is room to contribute back.

Ok that's fair. Is that something you'd like me to try and incorporate in this PR or write another issue (file it under tech debt haha) and tackle later? Just trying to make sure there's nothing remaining in my actions list on this one

2024-08-28 22:51 UTC, brandtkeller commented
> > Removes the need for that argument check ,improves native cobra flow and should provide more input validation.
> 
> So I was thinking about this more and wondering if that truly is more "native cobra" - as the Run command expects `args` and this will not run without that argument, so I'm wondering why is it bad to have that check (`len(args)==0`) ? I agree that it's more aligned with our other usage of flags, but also wondering if we should think more about the conventions we've set up for ourselves. If we are constantly having to put -f for a completely mandatory input, is that really desirable? Should flags be more in the realm of optional or intended to have alternative behaviors or additional functionality, as opposed to enforcing mandatory fields (e.g., file inputs)...
> 
> Anyway, I can change this, it's more just a thought about why/when to use flags vs args.

"native cobra" may not be fully capturing intent - but I do want to be iterating towards both flags and args having more strict control using cobra builtins such that we're improving our intended user experience without having to instrument that behavior for each command. 

Things such as combining required flag definitions with different permutations of [argument use](https://github.com/spf13/cobra/blob/main/site/content/user_guide.md#positional-and-custom-arguments) such that the pattern improves.

2024-08-29 14:47 UTC, brandtkeller commented
> > I'd lean towards TeaTest given that we manage that dependency accordingly. I'd like to review capabilities (again maybe a separate issue) and annotate gaps -> maybe there is room to contribute back.
> 
> Ok that's fair. Is that something you'd like me to try and incorporate in this PR or write another issue (file it under tech debt haha) and tackle later? Just trying to make sure there's nothing remaining in my actions list on this one

New issue to track testing -> would like to gauge interest in getting the testing structure in place prior to additional TUI feature development.

2024-08-29 16:47 UTC, meganwolf0 commented
For posterity, #627 opened to address testing

2024-08-29 17:45 UTC, brandtkeller requested changes
Minor comments but otherwise love the direction this sets. 

 The current structure I believe lends itself well to current thoughts around reporting - where we might be able to pass in multiple OSCAL files and establish an `oscalModel` that contains a valid artifact for each model (maybe this is multiple `-f` flags populating the full `oscalModel` object etc). 
 
 This creates a wholistic context of how the pieces connect to one-another and the ability to execute actions (validate etc) from this view will be fun to pursue.

2024-08-29 17:45 UTC, brandtkeller commented on docs/console/README.md
> +The Lula Console is a text-based terminaluser interface that allows users to interact with the OSCAL documents in a more intuitive and visual way.
```suggestion
The Lula Console is a text-based terminal user interface that allows users to interact with the OSCAL documents in a more intuitive and visual way.
```

2024-08-29 17:45 UTC, brandtkeller commented on docs/console/README.md
> +# Console
Agree that we will want separate documentation from the CLI commands for `console`. Just making sure you intended for this to be a root level docs directory such that it will have it's own header/nav-bar-item on the docs homepage?

2024-08-29 18:26 UTC, brandtkeller commented
Maybe last item: Can you switch `log_level` to `info` in the `lula-config.yaml` and run:
```bash
./bin/lula internal gen-cli-docs
```

Should only create a doc for the new console command.

2024-08-30 12:30 UTC, meganwolf0 commented on docs/console/README.md
> +# Console
Yeah - I wasn't really sure where to put this to be honest. Root level felt like very aggressively showy, but it also didn't feel like it aligned to any of the other current sections? If you have other thoughts on where this belongs then certainly all ears!

2024-08-30 13:07 UTC, brandtkeller commented on docs/console/README.md
> +# Console
Let's keep it and push forward

2024-08-30 13:11 UTC, brandtkeller approved these changes

2024-08-30 13:47 UTC, merged