feat(validate): resources added to backmatter
defenseunicorns-labs/lula1 pull request #612
Opened 2024-08-21 16:23 UTC by meganwolf0

## Description

Adds a flag `save-resources` to `validate` to save the resources to the backmatter of an assessment result

## Related Issue

Relates to #301

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-08-30 18:59 UTC, brandtkeller requested changes
Documenting for posterity:

Moving forward with consideration of the use of back matter more carefully. If we can meet our outcomes with a separate external file as-is today - we should execute on that strategy now while evaluating whether we continue to repeat the back matter storage pattern.

2024-09-03 15:07 UTC, meganwolf0 commented
Removed back-matter option and associated code changes needed, definitely simplifies things!

2024-09-10 16:47 UTC, brandtkeller requested changes
Few items to cleanup. Also understand this was a discovery and exploration driven PR as opposed to a direct issue deliverable - so I have no issues with undocumented requirements/additions (in the issue).

2024-09-10 16:47 UTC, brandtkeller commented on src/cmd/validate/validate.go
> +		if outputFile == "" {
Are we taking a stance towards standardizing the output of artifacts to be co-located with the targeted input file by default? 

If that was the intent - wanted to ensure we update the issue we have open to reflect a decision being made.

2024-09-10 16:47 UTC, brandtkeller commented on src/cmd/evaluate/evaluate.go
> +		if machine {
Can you help me understand what drives the need for this requirement? 

I need to find a good test that will highlight it's value - but I am failing to come up with the intuitive need for `Print a machine-readable output` when that is the point of OSCAL and what we do by default. 

^ that is mainly just the story telling piece - obviously this drills down into observations and may be another helpful flag - I'm just looking to understand the requirement so that we can tell a unified story.

2024-09-10 16:47 UTC, brandtkeller commented on src/pkg/common/oscal/assessment-results.go
> +				Ns:    "https://docs.lula.dev/oscal/ns/validation",
```suggestion
				Ns:    "https://docs.lula.dev/oscal/ns",
```

2024-09-10 16:47 UTC, brandtkeller commented on src/pkg/common/oscal/assessment-results.go
> +				Name:  "validation",
Need to update docs for this new property

2024-09-10 16:47 UTC, brandtkeller commented on src/pkg/common/oscal/assessment-results.go
> +	// TODO: should the props be added regardless?
Is this `validation` prop being consumed somewhere?

2024-09-10 19:20 UTC, meganwolf0 commented on src/cmd/validate/validate.go
> +		if outputFile == "" {
I was thinking yeah - since we say that `composed` files are co-located with the input-file location by default - and to me this makes more sense then it being at whatever directory you run the command from. I think there is an issue that kind of covers this, but happy to have more of a discussion around it. I just needed to enforce a location so I could write the resources there as well. And if it was in the working directory I didn't like how the resources would also be added there. 
Are you good with that change? Where should I update stuff if so, I'm not sure any docs right now specify default file location for `assessment-results`, but will need to double check that

2024-09-10 19:21 UTC, meganwolf0 commented on src/cmd/evaluate/evaluate.go
> +		if machine {
yeah this part is literally just returning a string that I can tell chatgpt to specifically look for and write follow-on commands given the content. I hid this flag deliberately because it makes no sense to an end user, maybe there's a better name though

2024-09-10 19:22 UTC, meganwolf0 commented on src/cmd/evaluate/evaluate.go
> +		if machine {
we also do a thing where we write to stderr - I could change to writing this machine data to stdout, since it's supposed to be some structured data... Idk that is probably wrapped up in a larger discussion of logging things, I just went with this because it was the easiest to implement as a gap filler

2024-09-10 19:25 UTC, meganwolf0 commented on src/pkg/common/oscal/assessment-results.go
> +	// TODO: should the props be added regardless?
not currently, the [PR](https://github.com/defenseunicorns/lula/pull/622/files#diff-90d2f3923e5be375196f94724668ca04eb49d12ec3cb29c6bd369e8dd54d4ed8) I have in draft (and will need to deconflict with this) has some sample dev print-x commands that use this prop

2024-09-10 19:43 UTC, meganwolf0 commented on src/pkg/common/oscal/assessment-results.go
> +	// TODO: should the props be added regardless?
Before I update the docs, I think maybe this question stands as something to answer - right now this prop is intended to provide a linkage back to the source validation, we don't actually have any mechanism to do so. Should this be added regardless of if the resources are saved? To me it seems like it would be helpful

2024-09-11 22:10 UTC, brandtkeller commented on src/cmd/validate/validate.go
> +		if outputFile == "" {
I don't have any strong concerns - I can't think of any current use that will be broken.

2024-09-19 18:53 UTC, brandtkeller commented on src/pkg/common/oscal/assessment-results.go
> +	// TODO: should the props be added regardless?
It provides a traceable pattern that we can refer to in the event we need to modify.

2024-09-19 18:55 UTC, brandtkeller commented on src/cmd/evaluate/evaluate.go
> +		if machine {
If you see a requirement of stdout here then that sounds like a good approach.

2024-09-20 15:12 UTC, meganwolf0 commented on src/pkg/common/oscal/assessment-results.go
> +				Name:  "validation",
added docs for this

2024-09-20 15:13 UTC, meganwolf0 commented on src/cmd/evaluate/evaluate.go
> +		if machine {
Ok, I updated this a bit -
I modified to a json output, since that feels more inline with what should go to stdout. Added a test for the GetMachineFriendlyObservations function.
Now if you run like a out=$(lula evaluate -f assessment-results --machine), the out will just be that json structure

2024-09-23 16:12 UTC, brandtkeller approved these changes

2024-09-23 16:13 UTC, merged