610 console component definition write
defenseunicorns-labs/lula1 pull request #648
Opened 2024-09-08 17:40 UTC by meganwolf0

## Description

updates to allow for write of the `remarks` and `description` fields of the component definition. Other "quality of life" updates with respect to simplifying views also incorporated.

## Related Issue

Fixes #610 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-09-11 23:35 UTC, brandtkeller reviewed
These are some massive PR's but totally understand there may not be a better way to slice them. 

Making my way through currently - Don't want to needlessly block these but still processing how best to review (and have the team review)

2024-09-11 23:35 UTC, brandtkeller commented on docs/console/component-definition.md
> +The `oscal-component.yaml` will need to be a valid OSCAL model - to use with the Component Definition view, it must contain the `component-definition`.
```suggestion
The `oscal-component.yaml` will need to be a valid OSCAL model - to use with the Component Definition view, it must contain the `component-definition` top level key.
```

Or something similar

2024-09-11 23:35 UTC, brandtkeller commented on src/cmd/console/console.go
> +			// f, err := tea.LogToFile("debug.log", "debug")
Intending to keep this code?

2024-09-19 21:29 UTC, brandtkeller reviewed
stoked about the functionality and seriously think there is huge long-term value for iteration. 

I ran into an inconsistency once where I made an edit -> saved -> attempted to quit and was told there was pending changes to save -> couldn't reproduce it though but now understand that save check even better. 

There are minor outstanding comments - If we resolve then I will do a final review.

2024-09-20 13:11 UTC, meganwolf0 commented on docs/console/component-definition.md
> +The `oscal-component.yaml` will need to be a valid OSCAL model - to use with the Component Definition view, it must contain the `component-definition`.
updated

2024-09-20 13:11 UTC, meganwolf0 commented on src/cmd/console/console.go
> +			// f, err := tea.LogToFile("debug.log", "debug")
removed

2024-09-20 14:09 UTC, brandtkeller requested changes

2024-09-20 14:09 UTC, brandtkeller commented on src/internal/tui/model.go
> +			m.saveModel.Open = true
I believe you'll want some additional handling in this to account for:

- Edit a compdef remarks field for any given control
- Attempt to quit with `ctrl+c`
- The `closeModel` will notify you that your `changes not written`
- Attempt to save with `ctrl+s` (this does nothing currently)

2024-09-20 15:43 UTC, meganwolf0 commented on src/internal/tui/model.go
> +			m.saveModel.Open = true
@brandtkeller sorry I'm not following all the keystroke use cases here, lmk if you have time to sync up and walk me through the operations you are trying to satisfy

2024-09-20 21:35 UTC, brandtkeller commented on src/internal/tui/model.go
> +			m.saveModel.Open = true
workflow addressed

2024-09-20 21:37 UTC, brandtkeller approved these changes
Outstanding work - appreciate the significance in enabling what will become essential to adoption.

2024-09-20 22:09 UTC, merged