feat(template)!: sample sensitive config
defenseunicorns-labs/lula1 pull request #672
Opened 2024-09-18 17:32 UTC by meganwolf0

## Description

Sample implementation for sensitive and non-sensitive configuration data to support templating

## Related Issue

Relates to #641

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-09-18 22:25 UTC, brandtkeller requested changes
I am a fan of this direction - called out a few items we may want to think about but otherwise this meets our requirements. 

I looked for any concerns or risks present with the nested brace replacement and did not find any issues. 

A lot of commonality between our approaches made this an easy review.

2024-09-18 22:25 UTC, brandtkeller commented on src/internal/template/template.go
> +	tpl.Option("missingkey=zero")
Although not entirely intuitive - I believe this will error under some known scenarios due to the use of a nested key in `constants` and how `missingkey=zero` works. I believe you'd want `missingkey=default` instead.

To reproduce:
```
./bin/lula tools template -f src/test/e2e/standard/validation.tpl --sensitive
```

Note the unexpected error instead of the `the zero value for the map type's element`

2024-09-18 22:25 UTC, brandtkeller commented on src/cmd/tools/template.go
> +		if templateOpts.Const {
We may want some error handling here for the inclusion of multiple flags which are not currently supported in a single execution. 

IE if I run `lula tools template -f file.yaml --const --all`

2024-09-19 20:24 UTC, brandtkeller commented
Additionally can we update the go mod/sum files when preparing for next review?

2024-09-20 01:00 UTC, meganwolf0 commented on src/internal/template/template.go
> +	tpl.Option("missingkey=zero")
I think per the conversation in slack, modified to missingkey=error to try and expose errors as early as possible

2024-09-20 01:00 UTC, meganwolf0 commented on src/cmd/tools/template.go
> +		if templateOpts.Const {
yeah, this was a dumb testing thing - I update this so you're just passing a single render type

2024-09-20 01:02 UTC, meganwolf0 commented
> Additionally can we update the go mod/sum files when preparing for next review?

When you say update - is there a particular package you were looking at or just like a `go mod tidy` cleanup?

2024-09-20 01:08 UTC, meganwolf0 commented
So I spent a little more time on this then I was initially planning and did some refactor of the internal/template package + the command. I was running into some issues when testing the cmd where the flags getting set were persisting across runs - which is not ideal. I refactored this so that we don't have external to the command flags, I've seen this in other repos and tbh I like that pattern better, seems to reduce side effects when testing.

This is 99% of the way ready for review, still need to update the configuration docs

2024-09-24 10:48 UTC, meganwolf0 commented on src/cmd/tools/template.go
>  	common.InitViper()
Also - is this redundant with the InitViper called at root? We have this in all the commands and I don't think I gave it much thought before but digging into the viper package we have I don't think we actually need to invoke this?

2024-09-24 21:06 UTC, brandtkeller commented on src/cmd/tools/template.go
> +	lula tools template -f ./oscal-component.yaml --set var.key1=value1 --set const.key2=value2
```suggestion
	lula tools template -f ./oscal-component.yaml --set .var.key1=value1 --set .const.key2=value2
```

2024-09-24 21:40 UTC, brandtkeller commented on src/cmd/tools/template.go
>  	common.InitViper()
I believe you are correct - I can't find a permutation where this needs to be executed here. 

Let's adjust this in a separate issue/pr such that we can trace origins of the change in the event it does break something. 

(I'd also like to include some scope in that issue which documents how `init()` is meant to be used such that we have evidence to support the change.

2024-09-24 21:41 UTC, brandtkeller requested changes
Super minor inconsistency in the help command. quick modification and re-generation of the cli doc and I'm good!

2024-09-25 21:08 UTC, brandtkeller approved these changes

2024-09-25 21:16 UTC, brandtkeller commented on src/cmd/tools/template.go
>  	common.InitViper()
Thinking on this more - it's certainly not explicitly required for commands - but it is used on a per-command basis when we perform lookups of viper configurations during the `init()` process. 

(Getting the content of an environment variable that Viper has automatically registered requires `GetString()` or applicable operation)

2024-09-25 22:30 UTC, merged