642 template files during persistent writes
defenseunicorns-labs/lula1 pull request #686
Opened 2024-09-27 01:10 UTC by meganwolf0

## Description

...

## Related Issue

Fixes #642 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-10-01 18:50 UTC, meganwolf0 commented
Noticed when testing that case-sensitive keys in `constants` don't turn into case-sensitive keys in the map[string]interface{} that's created from that key (viper thing) - added a note in the configuration.md and filed associated [issue](https://github.com/defenseunicorns/lula/issues/695)

2024-10-02 12:41 UTC, mildwonkey commented on src/pkg/common/composition/composition.go
> +type CompositionContext struct {
I like the pattern!

This is nitpicky, and I am not going to fight for a change here, just want to see what you think. Calling this a context when it isn't actually a `context.Context` is unintuitive to me, especially since you're also using context in the  `ComposeComponentDefinitions ` method. When I see something called a context I'd expect to get values from it using for e.g. `myCompositionCtx.Value(common.LulaWorkDir)`.  What do you think?

2024-10-02 15:38 UTC, meganwolf0 commented on src/pkg/common/composition/composition.go
> +type CompositionContext struct {
yeah that's totally fair - I guess I was thinking `context` like in that it contains the information needed to "compose" a component definition, but yeah if that's not intuitive/you have another word that could make sense there totally happy to change it!

2024-10-02 17:28 UTC, mildwonkey commented on src/cmd/tools/compose.go
> +				inputFile = filepath.Join(filepath.Dir(inputFile), filepath.Base(inputFile))
I'm not sure what this is meant to do - `filepath.Dir()` gets the directory from the input, stripping out the file name, it does not calculate the absolute path. As written, this results in the same thing as the inputFile (same as the outputFile below)

2024-10-03 12:10 UTC, meganwolf0 commented on src/cmd/tools/compose.go
> +				inputFile = filepath.Join(filepath.Dir(inputFile), filepath.Base(inputFile))
Ah yep good call - I kept mixing up Dir and Abs - I'll fix it!

2024-10-03 13:27 UTC, meganwolf0 commented on src/cmd/tools/compose.go
> +				inputFile = filepath.Join(filepath.Dir(inputFile), filepath.Base(inputFile))
on second thought, just decided to remove those - I don't actually think I need them (the only place I care about the absolute path is for the input file, which I'm calculating in the composition options)

2024-10-03 23:11 UTC, brandtkeller reviewed
Partial review - getting a baseline understanding and a super minor fix.

2024-10-03 23:11 UTC, brandtkeller commented on src/cmd/tools/compose.go
> +				message.Fatalf(err, "Output file %s is not a valid OSCAL model: %v", outputFile, err)
Should this be returning an error instead of executing the fatal function?

2024-10-03 23:31 UTC, meganwolf0 commented on src/cmd/tools/compose.go
> +				message.Fatalf(err, "Output file %s is not a valid OSCAL model: %v", outputFile, err)
yep! nice catch

2024-10-07 22:27 UTC, brandtkeller requested changes
Review cont - Can we run `lula internal gen-cli-docs` to update docs?

2024-10-07 22:27 UTC, brandtkeller commented on src/pkg/common/composition/resource-store.go
> +func createTemplateResource(data []byte) *oscalTypes_1_1_2.Resource {
Is this unused now that we had discussed not using `props` until we have solid evidence to support when and where to use them?

2024-10-08 13:58 UTC, meganwolf0 commented on src/pkg/common/composition/resource-store.go
> +func createTemplateResource(data []byte) *oscalTypes_1_1_2.Resource {
yep, removed!

2024-10-08 14:44 UTC, brandtkeller approved these changes

2024-10-08 14:46 UTC, brandtkeller commented on src/pkg/common/composition/composition.go
> +type CompositionContext struct {
Given the scope for which this is used - we can continue to iterate on naming if we find a better title.

2024-10-08 14:46 UTC, merged