[DRAFT] feature: file domain
defenseunicorns-labs/lula1 pull request #688
Opened 2024-09-27 13:58 UTC by mildwonkey

## Description

...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [X] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-09-27 16:01 UTC, brandtkeller reviewed
I appreciate the direction this is driving and the conciseness of the current implementation. 

Your identified constraints for what we do/do-not allow are certainly worth working through. I believe we're at a phase where constraints are valid if documented such that we can point to them - but would love to continue to weigh approaches. 

When it comes to testing - I do want to call out that this should work with any provider - the conftest/opa overlay is obviously very opa heavy (as is much of our implementation with Lula - as OPA/rego is quite powerful) but we do want to ensure we're also testing against the Kyverno baseline. Something we need to practice more often.

2024-09-27 16:59 UTC, mildwonkey commented
@brandtkeller yep! I am VERY CONCERNED about how this works with kyverno - honestly I am a bit surprised by how separate the domains and providers are, because I can see a world where certain providers can only support certain domains, or where the domain resources need to be gathered by the provider  so we're certain we're getting a provider-compliant output. That concerns me!

2024-09-30 10:41 UTC, meganwolf0 requested changes

2024-09-30 10:41 UTC, meganwolf0 commented on src/pkg/domains/files/files.go
> +	g := getter.DefaultClient
We have a `src/common/pkg/network` package (specifically the `Fetch` method) that I think we could also use here

2024-09-30 10:41 UTC, meganwolf0 commented on src/pkg/domains/files/files.go
> +func (d Domain) IsExecutable() bool { return false }
fwiw, I agree with the non-executable stance - `lula validate` will write a file anyway, so feels like writing tmp files locally is within the purview of the accesses provided to Lula

2024-09-30 10:41 UTC, meganwolf0 commented on src/pkg/domains/files/files_spec.go
> +	Filepaths []string
I think it would be good to allow for naming here - that's sort of our convention with the rest of the domains and that's what would be keyed on in the `provider`. If you have like a long ugly filename it might be kind of annoying to have to key on that down in the provider section. Also I think just makes it slightly easier to swap if file names/locations change

2024-09-30 10:41 UTC, meganwolf0 commented on src/pkg/domains/files/files.go
> +	g := getter.DefaultClient
I think this is also going to struggle when we put it into an actual `validate` workflow - I think we might have to do some passing with the cwd to handle any kind of relative paths because I believe if you execute from not the cwd the relative path gets bonked (I did some updates on `Fetch` to handle some of the wonky file dir changes [here](https://github.com/defenseunicorns/lula/pull/686/files#diff-94793c325bcfb4197d156903e7feac6b8482ec11140af38e1333ff8e132c2d19))

2024-09-30 10:44 UTC, meganwolf0 commented
> we do want to ensure we're also testing against the Kyverno baseline

Does kyverno polices support any data schema or just Kubernetes resources? I should probably know the answer but a quick parsing of their docs seems to indicate it's highly coupled to that format... if so I don't know how we'd use it here

2024-09-30 12:45 UTC, mildwonkey commented on src/pkg/domains/files/files.go
> +	g := getter.DefaultClient
I like go-getter better for this because it can pull from a longer list of sources, and it pulls directories, and I envisioned pulling things like entire git repos, s3 buckets, and terraform modules into it. If anything I'd replace recommend replacing `Fetch` with go-getter for that reason.

I'm already handling the relative path changing, that's not been an issue in validate, unless I'm misunderstanding something; I'll keep an eye out for issues there.

2024-09-30 13:25 UTC, mildwonkey commented on src/pkg/domains/files/files.go
> +func (d Domain) IsExecutable() bool { return false }
thanks! I cleaned up the comment based on feedback <3

2024-09-30 13:26 UTC, mildwonkey commented on src/pkg/domains/files/files_spec.go
> +	Filepaths []string
👍🏻 done!

2024-09-30 13:27 UTC, mildwonkey commented on src/pkg/domains/files/files.go
> +	g := getter.DefaultClient
👍🏻  I replaced go-getter w/ network.Fetch for. consistency (for now!)

2024-09-30 13:28 UTC, mildwonkey commented
> > we do want to ensure we're also testing against the Kyverno baseline
> 
> Does kyverno polices support any data schema or just Kubernetes resources? I should probably know the answer but a quick parsing of their docs seems to indicate it's highly coupled to that format... if so I don't know how we'd use it here

[`kyverno-json`](https://github.com/kyverno/kyverno-json) can be used with any arbitrary json-formatted data, so it does work reasonably well with the output of `DomainResources`. The UX is icky though, IMO, but I barely know kyverno and OPA so I'm hoping I come to like it with time (and of course as far as I know I'm doing this the clunkiest way possible):

```yaml
provider:
  type: kyverno
  kyverno-spec:
    policy:
      apiVersion: json.kyverno.io/v1alpha1
      kind: ValidatingPolicy
      metadata:
        name: grafana-config
      spec:
        rules:
        - name: protocol-is-https
          assert:
            all:
            - check:
                goodconfig.ini:
                  server:
                    protocol: https
```

2024-09-30 21:03 UTC, brandtkeller requested changes
Appreciative of the code comments and not withstanding the mention of E2E tests am quite excited about this capability.

2024-09-30 21:03 UTC, brandtkeller commented on docs/reference/domains/file-domain.md
> +## Validations
We don't yet have a good pattern for the mapping of domain -> provider. 

That said - I do like the Kyverno example below. Could we add an OPA provider example as well?

2024-09-30 21:03 UTC, brandtkeller commented on src/pkg/domains/files/files.go
> +	// istead of the file path.src/pkg/domains/files/files.go
```suggestion
	// instead of the file path.src/pkg/domains/files/files.go
```

2024-10-01 16:36 UTC, mildwonkey commented on src/pkg/domains/files/files.go
> +	// istead of the file path.src/pkg/domains/files/files.go
I fixed the rest of the line too thank you!

2024-10-01 16:47 UTC, mildwonkey commented on docs/reference/domains/file-domain.md
> +## Validations
I don't think the writing is very good but I added an OPA example! please nitpick freely.

2024-10-01 19:53 UTC, mildwonkey commented
I'm still working on this, but I'm going to split it up into a couple of smaller PRs (probably, either way I'm cleaning this mess up)(messing with directories is always a fun time)

2024-10-01 19:53 UTC, closed without merging