feat(generate): support for profile model and basic generation
defenseunicorns-labs/lula1 pull request #694
Opened 2024-10-01 02:35 UTC by brandtkeller

## Description

Adds initial support for the profile model with some very basic generation functionality to build upon. 

Looking to implement an OSCAL model interface for two reasons:
1. validate the necessity of the interface across models
2. experiment now vs future alignment with the underlying library possibly changing

There is a lot to unpack with support for a new model. Doing research and looking to document findings but ultimately believe the majority of complexity will be wrapped into processing of a profile for use with another model (either upstream in a catalog or downstream in a component/ssp). 

Intent is to document and further decompose both profile issues as well as oscal model issues. 

## Related Issue

Fixes #67 

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-10-10 12:50 UTC, meganwolf0 requested changes
probably going to play with it more/give more thought to the OSCALModel interface, but just to kick back some thoughts as a starter

2024-10-10 12:50 UTC, meganwolf0 commented on docs/cli-commands/lula_generate_profile.md
> +  -s, --source string        the path to the source catalog/profile
Is this the same thing as the -c/--catalog from generate component? Maybe using the same flags would be good there if so

2024-10-10 12:50 UTC, meganwolf0 commented on src/cmd/generate/generate.go
> +var profileExample = `
Total organizational nit, should we split the profile generation cmd out to a separate file? I could see the generate starting to grow and might make it a bit easier from like a "finding things" perspective? Maybe like a `generate` root that adds the commands? Food for thought.

2024-10-10 12:50 UTC, meganwolf0 commented on src/pkg/common/oscal/profile.go
> +					sort.Slice(includes, func(i, j int) bool {
More of an FYI if we want to implement - I added a function that I'm using in the console to sort controls, that does like a smarter sort if they're XX-##.## format
```
slices.SortStableFunc(controls, func(a, b control) int {
	return oscal.CompareControlsInt(a.title, b.title)
})
```

2024-10-10 12:50 UTC, meganwolf0 commented on src/cmd/generate/generate.go
> +	profilecmd.Flags().StringSliceVarP(&exclude, "exclude", "e", []string{}, "comma delimited list of controls to exclude from the source catalog/profile")
I think there was a comment down in the profile section, that `include` and `exclude` shouldn't be specified at the same time - I think `profilecmd.MarkFlagsMutuallyExclusive("include", "exclude")` might work here?

2024-10-10 12:50 UTC, meganwolf0 commented on src/test/e2e/cmd/generate_profile_test.go
> +func TestGenerateProfileCommand(t *testing.T) {
I tried generating a profile with some invalid include/exclude controls, and it didn't scrub those to say they weren't in the source/catalog. IDK how the `include-control`/`exclude-controls` parameter works exactly (or if it would even falter if invalid control IDs were put there) but just wondering if we should include a check on if those control IDs are in the catalog or not.

2024-10-10 15:11 UTC, brandtkeller commented on docs/cli-commands/lula_generate_profile.md
> +  -s, --source string        the path to the source catalog/profile
This is proposing a singular flag to be used for both profile/catalog sources and a previously captured request #563 would align generate component. 

Thoughts?

2024-10-10 15:12 UTC, brandtkeller commented on src/cmd/generate/generate.go
> +var profileExample = `
I agree - will separate.

2024-10-10 17:30 UTC, brandtkeller commented on src/test/e2e/cmd/generate_profile_test.go
> +func TestGenerateProfileCommand(t *testing.T) {
I made a note about this in the doc I forgot to create initially. Right now we do no validation that controls specified exist in the source. We don't ingest the source at all currently. This just gets you from A- > B with profile creation. 

Besides the validation of existence - nothing is ultimately transient between the source and profile. This validation will be common as we port component generation over to using `source` as well.

2024-10-10 17:30 UTC, brandtkeller commented on src/cmd/generate/generate.go
> +	profilecmd.Flags().StringSliceVarP(&exclude, "exclude", "e", []string{}, "comma delimited list of controls to exclude from the source catalog/profile")
Added! great call out for cobra implementation improvements.

2024-10-10 17:30 UTC, brandtkeller commented on src/pkg/common/oscal/profile.go
> +					sort.Slice(includes, func(i, j int) bool {
Added!

2024-10-10 20:57 UTC, CloudBeard commented on src/cmd/generate/profile.go
> +			if exists {
I don't think this is a prevent PR item but I noticed you can't re-run the generate command to overwrite a profile you created.

IE running the following command twice

`bin/lula generate profile -s https://raw.githubusercontent.com/GSA/fedramp-automation/refs/tags/fedramp-2.0.0-oscal-1.0.4/dist/content/rev5/baselines/yaml/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.yaml -i ac-1,ac-2,ac-3`

Or running either combo of the following commands

`bin/lula generate profile -s https://raw.githubusercontent.com/GSA/fedramp-automation/refs/tags/fedramp-2.0.0-oscal-1.0.4/dist/content/rev5/baselines/yaml/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.yaml -i ac-1,ac-2,ac-3`

`bin/lula generate profile -s https://raw.githubusercontent.com/GSA/fedramp-automation/refs/tags/fedramp-2.0.0-oscal-1.0.4/dist/content/rev5/baselines/yaml/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.yaml -i ac-1,ac-2`

You'll get `Error: output File profile.yaml currently exist - cannot merge artifacts`

You can do that with component-definitions is the only reason I noticed.

2024-10-10 21:07 UTC, CloudBeard commented
I know this isn't OSCAL Schema compliant but Lula functionality wise what do you think about a situation where you want to create a profile for IL4 using FedRAMP Moderate that would introduce the need to add the control AU-5(1) which isn't in the baseline so that control should come from the FedRAMP High Baseline.

Im thinking command/functionality wise allowing multiple sources, have something like `-ia` (include-all, for Moderate baseline), and `-i` for the specific controls in High Baseline.

Reconcile what that would actually look like in OSCAL but a quick way to say give me all of FedRAMP Moderate and this control(s) from High.

2024-10-10 23:33 UTC, meganwolf0 commented on docs/cli-commands/lula_generate_profile.md
> +  -s, --source string        the path to the source catalog/profile
Ok after looking at the issue and back at the commands... is the logic to handle either (to populate the component or profile) different? Would it be better from a consuming that source perspective to have those indicated differently (just so you avoid having to try and read the doc not knowing up front what it is)? Given my OSCAL-ese is pretty bad, I'd defer to you all on that one. 

Doesn't look like component currently supports Profile, although the flag is available, so I can't really tell the difference between what happens under the hood if either is chosen...

2024-10-10 23:34 UTC, meganwolf0 commented on docs/cli-commands/lula_generate_profile.md
> +  -s, --source string        the path to the source catalog/profile
And if I scroll down to the next comment, it sounds like maybe that's the answer to above - the source doesn't really matter?

2024-10-11 02:53 UTC, brandtkeller commented on docs/cli-commands/lula_generate_profile.md
> +  -s, --source string        the path to the source catalog/profile
The idea with source as used in profile and component definition is that it can point to either a profile or a catalog. 

So we have a TODO which is to support component-definitions pointing to either (and not knowing which until we read it into the complete schema. If we write this logic to support component-definitions - it can be re-used here in the future as the same logic. 

For the current scope - we're not doing any processing of what source is as of yet. In a follow on issue (i'll be decomposing these shortly) we'll be performing a profile-resolve which will need to utilize source. I wanted to keep this separate as it will introduce a lot of new logic.

2024-10-11 03:02 UTC, brandtkeller commented on src/cmd/generate/profile.go
> +			if exists {
Correct! `HandleExisting` is going to currently return an error for the profile model. There is a lot of complexity baked into what you can do with a profile and I believe initially I found merging to be a constraint. 

Thinking on it more and there will certainly be things that don't make sense with generation but merging might not be terrible. I'll give that a shot.

2024-10-11 04:05 UTC, brandtkeller commented on src/cmd/generate/profile.go
> +			if exists {
Added support for merging behaviors with 1 caveat:

Instead of trying to support every single permutation possible of include/exclude/all -> when a conflicting `import` is found during merge - the latest will take precedence and overwrite the original import of the same `href`. 

Maybe we can support more granularity in the future - but I'd like to see if/how this command is used.

2024-10-11 04:22 UTC, brandtkeller commented
> I know this isn't OSCAL Schema compliant but Lula functionality wise what do you think about a situation where you want to create a profile for IL4 using FedRAMP Moderate that would introduce the need to add the control AU-5(1) which isn't in the baseline so that control should come from the FedRAMP High Baseline.
> 
> Im thinking command/functionality wise allowing multiple sources, have something like `-ia` (include-all, for Moderate baseline), and `-i` for the specific controls in High Baseline.
> 
> Reconcile what that would actually look like in OSCAL but a quick way to say give me all of FedRAMP Moderate and this control(s) from High.
> 
> (Also don't think this blocks this PR, its more of a future request/thought)

I was going to move it off to another issue but you gave me to motivation to support an `--all` flag for importing all controls. 

I believe we can accomplish the scenario above with a few commands. Processing that will be another story and scope for another issue I will write.

2024-10-11 18:42 UTC, meganwolf0 commented
> I was going to move it off to another issue but you gave me to motivation to support an `--all` flag for importing all controls.

Trying to follow the train of thought in the thread, but would --all not be the default if include or exclude wasn't provided? I guess, what happens in no flag vs --all?

2024-10-11 20:22 UTC, brandtkeller commented
> Trying to follow the train of thought in the thread, but would --all not be the default if include or exclude wasn't provided? I guess, what happens in no flag vs --all?

Great point - that was a gap. Added a OneRequired for the flags to lean into explicit vs default.

2024-10-17 15:57 UTC, meganwolf0 approved these changes, later dismissed
Approved! Are we going to create follow-on issues to reconcile the `OSCALModel` interface across the other models we have?

2024-10-18 16:24 UTC, meganwolf0 approved these changes

2024-10-18 16:34 UTC, brandtkeller commented
> Approved! Are we going to create follow-on issues to reconcile the `OSCALModel` interface across the other models we have?

Added issues as referenced a few hours ago

2024-10-18 16:34 UTC, merged