feat: add brew install for lula
defenseunicorns-labs/lula1 pull request #707
Opened 2024-10-04 13:31 UTC by CloudBeard

## Description

Added Brew release configuration. This should create the release inside of the Defense Unicorns Brew repo. Permissions were previously setup. 

A separate issues exists for updating the documentation after a release has been cut and testing has bee conducted. https://github.com/defenseunicorns/lula/issues/321

This issue would be a follow on after a release has been made.

## Related Issue

Fixes #
#702 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-10-04 16:35 UTC, brandtkeller requested changes
Minor future proofing commands but i'd also like to make a request:

`goreleaser check` is returning errors and deprecations. While we're here I'd like to expand scope a small amount such that we have a repeatable process for these kinds of updates. 

- Ensure the configuration is valid per `goreleaser check`
- Document these checks in our release process (if applicable)

Besides that - as a practice I'd like to start capturing "how does a reviewer perform review of these changes" in our PR descriptions -> I'll work this into a PR template.

2024-10-04 16:35 UTC, brandtkeller commented on .goreleaser.yaml
> +    homepage: "https://github.com/defenseunicorns/lula"
Future Proof a little
```suggestion
    homepage: "https://lula.dev"
```

2024-10-04 16:35 UTC, brandtkeller commented on .goreleaser.yaml
> +    homepage: "https://github.com/defenseunicorns/lula"
```suggestion
    homepage: "https://lula.dev"
```

2024-10-04 19:16 UTC, CloudBeard commented on .goreleaser.yaml
> +    homepage: "https://github.com/defenseunicorns/lula"
Updated

2024-10-04 19:16 UTC, CloudBeard commented on .goreleaser.yaml
> +    homepage: "https://github.com/defenseunicorns/lula"
Updated

2024-10-04 19:17 UTC, CloudBeard commented
Added a GitHub Action that will run GoReleaser check on any pushes or PRs that contain a change to the .goreleaser.yaml file.

Also tweaked the wording a bit in our release documentation to call out the brew info and the action. We don't go too in-depth into distros.

2024-10-04 20:24 UTC, brandtkeller commented on docs/community-and-contribution/release-process.md
> +PR titles should also follow this pattern and are linted using [commitlint](https://commitlint.js.org/). The PR title will determine the version bump. When a PR is merged (squashed) release-please wi
```suggestion
PR titles should also follow this pattern and are linted using [commitlint](https://commitlint.js.org/). The PR title will determine the version bump. When a PR is merged (squashed) release-please will kick off a release PR. When that release PR is approved and merged, release-please will create a draft release. Once that draft release is published go-releaser with build and publish the assets, including creating a release in our Homebrew tap repository: [https://github.com/defenseunicorns/homebrew-tap](https://github.com/defenseunicorns/homebrew-tap)
```

2024-10-07 14:59 UTC, brandtkeller approved these changes

2024-10-07 15:00 UTC, merged