feat(validate): template oscal during runtime
defenseunicorns-labs/lula1 pull request #708
Opened 2024-10-04 13:40 UTC by meganwolf0

## Description

Lula validate with templating

## Related Issue

Fixes #592 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-10-09 17:20 UTC, mildwonkey commented on src/test/e2e/api_validation_test.go
> +			assessment, err := validationCtx.ValidateOnPath(context.Background(), oscalPath, "")
🤔  this naming convention is still really confusing; I looked at this and initially didn't understand why you weren't writing `ValidateOnPath(validationCtx, oscalPath, "")`  

This is one of the two main use cases for the `context.Context()` that I added to the root commands. It's good for passing request-specific contextual values. Is there a reason you didn't use that? 

If you don't want to use the `ctx` (which is valid, I just want to understand why we wouldn't use what's already there for that purpose), can we rename these so it's not quite so ambiguous? "context"  has a very specific connotation in go and naming a struct "anythingctx" or "anythingcontext" leads me to assume it is a `context.Context`, so I prefer not to use that in other ............... contexts. 😭

2024-10-09 23:37 UTC, meganwolf0 commented on src/test/e2e/api_validation_test.go
> +			assessment, err := validationCtx.ValidateOnPath(context.Background(), oscalPath, "")
Yeah we can call it something else instead of context, I was hoping you'd word-smith me something haha but we didn't really ever close it on compose so just left it as is... but idk, like ComposeBuilder/ValidationBuilder? I'm not a creative type.

> This is one of the two main use cases for the context.Context() that I added to the root commands.

Which part would I substitute out for using the context from the root? Not totally following there

2024-10-10 20:14 UTC, brandtkeller requested changes
I don't see much that looks unsuited to the task. Deconflicting with main and some cleanup - otherwise looks good.

2024-10-10 20:14 UTC, brandtkeller commented on src/pkg/common/composition/resource-store.go
> +func createTemplateResource(data []byte) *oscalTypes_1_1_2.Resource {
this is just a historical artifact that needs cleanup correct?

2024-10-10 23:20 UTC, meganwolf0 commented on src/pkg/common/composition/resource-store.go
> +func createTemplateResource(data []byte) *oscalTypes_1_1_2.Resource {
ah it snuck back in, removed!

2024-10-11 13:03 UTC, meganwolf0 commented on src/test/e2e/api_validation_test.go
> +			assessment, err := validationCtx.ValidateOnPath(context.Background(), oscalPath, "")
renamed!

2024-10-11 21:22 UTC, brandtkeller submitted a review, later dismissed

2024-10-11 22:55 UTC, brandtkeller approved these changes

2024-10-11 22:56 UTC, merged