chore(file domain): add network.DownloadFile and use go-getter to download files
defenseunicorns-labs/lula1 pull request #760
Opened 2024-10-24 15:09 UTC by mildwonkey

## Description
This PR adds a new method, `network.DownloadFile`, which users go-getter to download files. It's currently in use by the file domain. Go-getter's Get supports local files, network downloads (`network.Fetch` also already handles that!) and also a number of protocols such as ftp, s3, git, etc. 

I limited the functionality to downloading INDIVIDUAL FILES and not full directories and repositories _for now_, since it would take more testing and a slightly larger refactor of the file domain. (I have an idea for that, but wanted to get this PR dealt with first). A future PR will add `network.Download` for directories, git repos, etc. (This will require an additional field in the file spec, `source` or something similar. Users will still need to list the files that the validations run against).

I added one test that pulls a file from our git repo to the e2e tests. There is a comment in the file warning future-us of that, but it's still worth mentioning that will break and annoy us some day (and be easily fixed, but still. Annoying). 

There are some other changes in the e2e test files - It was getting hard to find the actual test output, so I removed all the calls to message.Info. I also noticed I had randomly started using assert where I wanted require in the files domain e2e tests, so that's fixed too 🙄 

...

## Related Issue
Relates to #693 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)
more of a precursor to a new feature, but close enough?

2024-10-25 10:06 UTC, meganwolf0 commented
Is the intent to completely move off network.Fetch, or is this supposed to just be like a separate functionality with the intent to support more specialized downloads specifically for the file domain?

Also, because I was just at a security conference and it's fresh, looking at like the dependencies for the current network package (which are all go built-ins) vs this PR which adds some super old/forked package deps (I'm sure we have a ton of that, honestly this is really the first time I'm really looking under the hood there), just thinking more about our posture on these kinds of things/potentially accepting risks. More of a team discussion I think though.

2024-10-25 12:37 UTC, mildwonkey commented
This isn't going to replace Fetch, since go-getter only writes files and most callers just need to read the bytes. My original files domain PR just used go-getter in the domain and I don't mind doing that again.

No argument on the general dependency concern, but if we make the domains external plugins, go-getter is the library I'd suggest we use to download them. It is indeed always a risk, but at least go-getter has a ton of attention on it thanks to several projects, instead of managing it all myself or trusting a library I've never heard of with 6 stars (side note, I'd love an approved go libraries list). Having said that, if we don't feel good about this, I have no problem closing it till we can discuss more.

2024-10-28 12:25 UTC, meganwolf0 commented
> This isn't going to replace Fetch

Ok great, I was thinking the original issue sort of indicated that but since not then sounds good to me!

> at least go-getter has a ton of attention on it thanks to several projects

Agreed, seems like there's a few big projects importing the library so not super concerned. I think just fresh off that conference it was more in the forefront of my mind that probably goes into the checklist for PR reviews.

2024-10-28 12:44 UTC, meganwolf0 requested changes

2024-10-28 12:44 UTC, meganwolf0 commented on src/test/e2e/file_validation_test.go
> +		require.NoError(t, err)
should we checked that the result was satisfied? The validations will fail gracefully even if a file couldn't be downloaded, so probably good to check that it passed because that'll actually be the check of the remote download

2024-10-29 14:06 UTC, brandtkeller commented on src/pkg/domains/files/files.go
> +		stringdir, err := os.MkdirTemp(dst, "string")
Do we need a temporary directory _for each_ file or would one suffice?

2024-11-03 21:08 UTC, brandtkeller commented on src/pkg/domains/files/files.go
> +		stringdir, err := os.MkdirTemp(dst, "string")
there may be an underlying reason for this - primarily just curious in the event we were to expose an option for a file cache on the filesystem.

2024-11-04 16:29 UTC, mildwonkey commented on src/pkg/domains/files/files.go
> +		stringdir, err := os.MkdirTemp(dst, "string")
This is a temp dir for all files by user-specified parser, not necessarily every individual file.

2024-11-05 04:24 UTC, brandtkeller commented on src/pkg/domains/files/files.go
> +		stringdir, err := os.MkdirTemp(dst, "string")
maybe my brain is broken tonight - we have this slice of unstructured files (string parser)- we iterate over each file and we create a temporary directory before performing the copy/read. 

Doesn't each loop create a new temporary directory?

2024-11-07 13:43 UTC, mildwonkey commented on src/pkg/domains/files/files.go
> +		stringdir, err := os.MkdirTemp(dst, "string")
No - in this code section you can look at the `dst` line: it's downloading just the file into the `stringdir`. It's not creating a directory for each file. All the unstructured files go to the "string" parser directory. 

Go-getter in file download mode accepts a full file path, not a directory, to install files into.

2024-11-07 18:58 UTC, brandtkeller approved these changes

2024-11-07 20:32 UTC, mildwonkey commented
@meganwolf0 - i did push the extra test validation you requested, does it look sufficient to you?

2024-11-07 21:06 UTC, meganwolf0 approved these changes

2024-11-08 13:18 UTC, merged