generate(ssp): initial generate ssp command
defenseunicorns-labs/lula1 pull request #812
Opened 2024-11-20 19:02 UTC by meganwolf0

## Description

Initial generate ssp command
* Adds `lula generate system-security-plan` with required component(s) and source/catalog
* ...

Notes on assumptions
* Assuming some form of composed component definitions(?) just validation links re-mapped?

Follow-on to this #810 

## Related Issue

Fixes #803

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-12-09 19:41 UTC, mildwonkey reviewed
I don't necessarily feel qualified to approve this (the oscal concepts are still so new to me), but I also don't have any objections and it all looks reasonable to me :) I left some comments but nothing that requires changes; feel free to dismiss 'em ❤️

2024-12-09 19:41 UTC, mildwonkey commented on docs/cli-commands/lula_generate_system-security-plan.md
> +Generation of a System Security Plan OSCAL artifact from a source profile along with an optional list of component definitions.
this is so nitpicky i'm sorry, but is it a template, or an artifact? Should this use the same terminology as the sentence above?

2024-12-09 19:41 UTC, mildwonkey commented on docs/oscal/system-security-plan.md
this is a really solid doc overall 👍🏻

2024-12-09 19:41 UTC, mildwonkey commented on src/test/e2e/cmd/generate_ssp_test.go
> +		assert.Equal(t, 3, len(sspModel.ControlImplementation.ImplementedRequirements), "expected 3 controls")
I have no objection and certainly don't want anything you've written removed, but fwiw adding error messages to the asserts is rarely valuable IMO - if our error messages aren't clear enough to us you why the test failed, that's a sign to fix the error message in the test

2024-12-09 23:21 UTC, brandtkeller commented on docs/oscal/system-security-plan.md
> +A [System Security Plan](https://pages.nist.gov/OSCAL/resources/concepts/layer/implementation/ssp/) is an OSCAL-specific model to represent a system as a whole. In Lula, the `generate system-security
"system as a whole" feels like potentially repetitive language. We can probably drop that in favor of "the system".

2024-12-10 21:22 UTC, brandtkeller commented on src/cmd/generate/system-security-plan.go
> +		component  []string
[nit] Would plural `components` be more intuitive to the user?

2024-12-11 01:56 UTC, brandtkeller reviewed
Few minor comments thus far - have a little more tracing to do - otherwise looking great.

2024-12-11 01:56 UTC, brandtkeller commented
(few conflicts to resolve when you have a minute)

2024-12-11 12:56 UTC, meganwolf0 commented on docs/oscal/system-security-plan.md
Thank you! @CloudBeard created this doc so props to him! I just updated some of it to reflect the new generation assumption 😄

2024-12-11 12:58 UTC, meganwolf0 commented on src/cmd/generate/system-security-plan.go
> +		component  []string
fair nit, I think you're right - will update

2024-12-11 12:58 UTC, meganwolf0 commented on docs/oscal/system-security-plan.md
> +A [System Security Plan](https://pages.nist.gov/OSCAL/resources/concepts/layer/implementation/ssp/) is an OSCAL-specific model to represent a system as a whole. In Lula, the `generate system-security
updating!

2024-12-11 13:03 UTC, meganwolf0 commented on docs/cli-commands/lula_generate_system-security-plan.md
> +Generation of a System Security Plan OSCAL artifact from a source profile along with an optional list of component definitions.
This is a fair nitpicky comment - and I think I'd prefer the language `artifact` as it's a valid OSCAL SSP. Although I do see in generate component and profile we used the language of `template` (which is where I copy-pasta'd from)... Template now has a very specific denotation within Lula so I'm not really sure that's the right language to use and we should probably consolidate around another phrase for the `generate` commands. 

@brandtkeller might have some thoughts.

2024-12-11 13:09 UTC, meganwolf0 commented on src/test/e2e/cmd/generate_ssp_test.go
> +		assert.Equal(t, 3, len(sspModel.ControlImplementation.ImplementedRequirements), "expected 3 controls")
That's fair - I generally haven't been adding error messages and tbh I'm not really sure what came over me on this one that provided the inclination to adding them 😅 
That is a good point about these err messages potentially obfuscating _bad_ error output from the functions though 🤔

2024-12-11 13:26 UTC, meganwolf0 commented
**Update**
* Resolved conflicts on main (with oscalTypes)
* Fixed some doc words
* Modified flag/var name for `component` -> `components` in generate SSP
* `template` -> `artifact` in short help for both SSP and Profile (Do we want to update generate component text as well OR is there another word we should give these things?)

Note - the `help.golden` files are kind of annoying since we have to re-generate the cli-docs + re-run the tests to generate the help docs when some command text words change... just throwing out the question of if those golden checks on `help` are valuable?

2024-12-12 21:26 UTC, brandtkeller commented on docs/cli-commands/lula_generate_system-security-plan.md
> +Generation of a System Security Plan OSCAL artifact from a source profile along with an optional list of component definitions.
I would agree with your assessment. `artifact` is more aligned to the story Lula should tell in the long run. We've described it as a template in the past - as it's not a "complete" artifact - but it is still an artifact nonetheless.

2024-12-12 22:30 UTC, brandtkeller requested changes
besides a typo I feel like this looks great and really sets us up well for AP generation.

2024-12-12 22:30 UTC, brandtkeller commented on src/cmd/generate/system-security-plan.go
> +				command += fmt.Sprintf(" --component %s", componentPath)
```suggestion
				command += fmt.Sprintf(" --components %s", componentPath)
```

2024-12-13 13:39 UTC, meganwolf0 commented on src/cmd/generate/system-security-plan.go
> +				command += fmt.Sprintf(" --component %s", componentPath)
ahh a `component` hold out, nice catch!

2024-12-13 15:05 UTC, mildwonkey approved these changes
🎉

2024-12-13 23:43 UTC, brandtkeller approved these changes

2024-12-13 23:43 UTC, merged