feat: validate run tests
defenseunicorns-labs/lula1 pull request #838
Opened 2024-12-05 19:30 UTC by meganwolf0

## Description

Instrument a test-report output for `lula validate ... --run-tests`

## Related Issue

Fixes #782

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-12-19 03:57 UTC, brandtkeller requested changes
Minor discrepancy in my review thus far.

2024-12-19 03:57 UTC, brandtkeller commented on docs/reference/testing.md
> +When executing `lula dev validate ... --run-tests`, the test results data will be written directly to console.
Documentation above mentions writing the results to a file (specifically markdown) whereas this references `directly to console` yet my local testing created a `.yaml` file.

2024-12-20 15:41 UTC, meganwolf0 commented on docs/reference/testing.md
> +When executing `lula dev validate ... --run-tests`, the test results data will be written directly to console.
ah sorry for the confusion - the behavior of `dev validate` is directly to console, `validate` prints a summary to console but the actual test results to a yaml doc. The md was an old thing and I'll update it! Mostly I just figured that printing test results to console for a single validation `dev validate` would be fine, but if you potentially had a ton you might want a separate output format?

2024-12-20 17:51 UTC, brandtkeller commented on docs/reference/testing.md
> +When executing `lula dev validate ... --run-tests`, the test results data will be written directly to console.
appreciate the clarity and distinction between the commands. I think I got a little lost there and didn't notice the difference between the two commands.

2024-12-20 18:29 UTC, brandtkeller approved these changes

2024-12-20 18:30 UTC, merged