840 validation tests path resolution
defenseunicorns-labs/lula1 pull request #845
Opened 2024-12-11 21:07 UTC by meganwolf0

## Description

...

## Related Issue

Fixes #840

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

2024-12-13 15:03 UTC, mildwonkey requested changes
One typo to fix, the other suggestions you are free to take or ignore as you see fit! This looks good, and I like your documentation.

2024-12-13 15:03 UTC, mildwonkey commented on docs/getting-started/develop-a-validation.md
> +    3) **Preferred Approach** Implement tests natively in the validation, using the [testing guide](../reference/testing.md). See the next tuturial [test a validation](./test-a-validation.md) for mor
typo!
```suggestion
    3) **Preferred Approach** Implement tests natively in the validation, using the [testing guide](../reference/testing.md). See the next tutorial [test a validation](./test-a-validation.md) for more information.
```

2024-12-13 15:03 UTC, mildwonkey commented on docs/getting-started/test-a-validation.md
> +  value: "0"
I might add a comment inline with this example to make it very clear that this version won't work - it's easy to start copy pasting snippets out of tutorials without realizing you're copying the "don't do it this way" version if it isn't labeled incredibly clearly

2024-12-13 15:03 UTC, mildwonkey commented on docs/getting-started/test-a-validation.md
> +However, this will not correctly generate the expected json structure, as the `replicas` field is a number, and not a string. Instead, we need to use the `value-map` change type, which allows us to s
If you're doing to do show a "not working" snippet, I think you should add also show the working snippet before putting it all together in the full example below - if you look at just the snippets and not the words we're telling a confusing story. (this isn't quite formatted properly as a suggestion)

```suggestion
However, this will not correctly generate the expected json structure, as the `replicas` field is a number, and not a string. Instead, we need to use the `value-map` change type, which allows us to set the value of a field to any type of value:
```

Then add the correct snippet below (formatting got weird, you get the idea)

```yaml
- path: podinfoDeployment.status
   type: update
   value-map: 
      replicas: 0
```

2024-12-13 15:03 UTC, mildwonkey commented on docs/reference/testing.md
> +* If you need to access a map key that is an integer, either use `foo["0"]` or `foo.0`
it's not that I don't believe you, but the `"0" in ``foo["0"]` does not look like an integer  - this is confusing! To access a map key that is an integer, pass in a string????? 😭

2024-12-16 13:25 UTC, meganwolf0 commented on docs/getting-started/test-a-validation.md
> +However, this will not correctly generate the expected json structure, as the `replicas` field is a number, and not a string. Instead, we need to use the `value-map` change type, which allows us to s
I showed the "right" way above, are you just thinking from like a better story-telling perspective it makes sense to start with the "wrong" way - like "a user may be inclined to do this thing <wrong way>, DONT do this thing, instead do this thing <right way>"?

2024-12-16 13:27 UTC, meganwolf0 commented on docs/reference/testing.md
> +* If you need to access a map key that is an integer, either use `foo["0"]` or `foo.0`
sorry, that is confusing wording. I guess I should say a string that only contains an integer? Because I don't think integer types are actually valid keys haha, so that's what I was after. Idk if you have some better words for that

2024-12-16 19:28 UTC, mildwonkey commented on docs/reference/testing.md
> +* If you need to access a map key that is an integer, either use `foo["0"]` or `foo.0`
Yeah, map keys are required to be strings, so it's a confusing statement. Might be clearer to just say "map keys must be strings so if you have an integer, wrap it in quotes"? or just "map keys are strings"

2024-12-16 19:30 UTC, mildwonkey commented on docs/getting-started/test-a-validation.md
> +However, this will not correctly generate the expected json structure, as the `replicas` field is a number, and not a string. Instead, we need to use the `value-map` change type, which allows us to s
🤔 My mistake, sorry! I clearly misread the document, I thought the "right way" you mentioned above was still part of the previous example. I'll resolve this 'cuz I don't have a suggestion, but I find it confusing (as someone to whom this is all new syntax) to be told how I would expect to do something, when that's not what I was thinking when reading that section. 

I'd personally like to see a comment in the invalid snippet that says `# invalid syntax` or something but now I'm just exposing that I look at the code snippets without reading 😂

2024-12-16 19:31 UTC, mildwonkey submitted a review, later dismissed
LGTM 👍🏻 

(I'll re-approve if you want to change the integer map key wording but my actual requested changes are resolved)

2024-12-16 19:54 UTC, mildwonkey approved these changes
I like the changes! 😀 ❤️ :shipit:

2024-12-20 18:55 UTC, brandtkeller approved these changes
I really like the `test-a-validation.md` doc.

2024-12-20 18:55 UTC, merged